export const PAYMENT_REPOSITORY_PROVIDER = 'PAYMENT_REPOSITORY';
export const PAYMENT_SERVICE_PROVIDER = 'PAYMENT_SERVICE';
export const PAYMENT_USECASE_PROVIDERS = {
  ADD_PAYMENT: 'ADD_PAYMENT',
  ADD_PAYMENTS: 'ADD_PAYMENTS',
  GET_PAYMENT: 'GET_PAYMENT',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT',
  QUERY_PAYMENTS: 'QUERY_PAYMENTS',
  CREATE_STRIPE_INVOICE: 'CREATE_STRIPE_INVOICE',
  CREATE_WEBHOOK_ENDPOINT: 'CREATE_WEBHOOK_ENDPOINT',
  HANDLE_STRIPE_WEBHOOK: 'HANDLE_STRIPE_WEBHOOK',
  UPDATE_STRIPE_API_KEY: 'UPDATE_STRIPE_API_KEY',
  CREATE_PAYTABS_INVOICE: 'CREATE_PAYTABS_INVOICE',
  PAYTABS_CALLBACK: 'PAYTABS_CALLBACK',
  RETRIEVE_STRIPE_BALANCE: 'RETRIEVE_STRIPE_BALANCE',
};
