export const PAYMENT_REPOSITORY_PROVIDER = 'PAYMENT_REPOSITORY';
export const PAYMENT_SERVICE_PROVIDER = 'PAYMENT_SERVICE';
export const PAYMENT_USECASE_PROVIDERS = {
  ADD_PAYMENT: 'ADD_PAYMENT',
  GET_PAYMENT: 'GET_PAYMENT',
  UPDATE_PAYMENT: 'UPDATE_PAYMENT',
  DELETE_PAYMENT: 'DELETE_PAYMENT',
  GET_PAYMENTS: 'GET_PAYMENTS',
};
