export const ETA_RECEIPT_PROCESSOR_PROVIDER = 'ETA_RECEIPT_PROCESSOR';
export const ETA_RECEIPT_SERVICE_PROVIDER = 'ETA_RECEIPT_SERVICE';
export const ETA_RECEIPT_QUEUE_PROVIDER = 'ETA_RECEIPT_QUEUE';

export const ETA_RECEIPT_USECASE_PROVIDERS = {
  SUBMIT_RECEIPTS: 'SUBMIT_RECEIPTS',
  CANCEL_RECEIPT: 'CANCEL_RECEIPT',
  PROCESS_RECEIPT: 'PROCESS_RECEIPT',
  ACCEPT_RECEIPT: 'ACCEPT_RECEIPT',
};
