export const RECEIPT_REPOSITORY_PROVIDER = 'RECEIPT_REPOSITORY';
export const RECEIPT_SERVICE_PROVIDER = 'RECEIPT_SERVICE';
export const RECEIPT_USECASE_PROVIDERS = {
  ADD_RECEIPT: 'ADD_RECEIPT',
  ADD_RECEIPTS: 'ADD_RECEIPTS',
  GET_RECEIPT: 'GET_RECEIPT',
  UPDATE_RECEIPT: 'UPDATE_RECEIPT',
  DELETE_RECEIPT: 'DELETE_RECEIPT',
  QUERY_RECEIPTS: 'QUERY_RECEIPTS',
};
