export const CODE_REPOSITORY_PROVIDER = 'CODE_REPOSITORY';
export const CODE_SERVICE_PROVIDER = 'CODE_SERVICE';
export const CODE_USECASE_PROVIDERS = {
  GET_CODE: 'GET_CODE',
  GET_CODES: 'GET_CODES',
  DRAFT_CODE: 'DRAFT_CODE',
  IMPORT_CODES: 'IMPORT_CODES',
  ADD_CODES: 'ADD_CODES',
  UPDATE_CODE: 'UPDATE_CODE',
  REUSE_CODE: 'REUSE_CODE',
};
