import { CountryCode, CountryTimezone } from '../enums';
import { Country } from '../models';

// TODO: FINSH THE US AND CA
export const Countries: Country[] = [
  {
    id: 1,
    code: CountryCode.AFGHANISTAN,
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    phoneCode: '+93',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/af.svg',
    timeZones: [CountryTimezone.AFGHANISTAN],
    offset: ['UTC +04:30'],
  },
  {
    id: 2,
    code: CountryCode.ALAND_ISLANDS,
    name: 'Aland Islands',
    nameAr: 'جزر ألاند',
    phoneCode: '+358',
    phoneMinLength: 8,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ax.svg',
    timeZones: [CountryTimezone.ALAND_ISLANDS],
    offset: ['UTC +02:00'],
  },
  {
    id: 3,
    code: CountryCode.ALBANIA,
    name: 'Albania',
    nameAr: 'ألبانيا',
    phoneCode: '+355',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/al.svg',
    timeZones: [CountryTimezone.ALBANIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 4,
    code: CountryCode.ALGERIA,
    name: 'Algeria',
    nameAr: 'الجزائر',
    phoneCode: '+213',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/dz.svg',
    timeZones: [CountryTimezone.ALGERIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 5,
    code: CountryCode.AMERICAN_SAMOA,
    name: 'American Samoa',
    nameAr: 'ساموا-الأمريكي',
    phoneCode: '+1-684',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/as.svg',
    timeZones: [CountryTimezone.AMERICAN_SAMOA],
    offset: ['UTC -11:00'],
  },
  {
    id: 6,
    code: CountryCode.ANDORRA,
    name: 'Andorra',
    nameAr: 'أندورا',
    phoneCode: '+376',
    phoneMinLength: 6,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ad.svg',
    timeZones: [CountryTimezone.ANDORRA],
    offset: ['UTC +01:00'],
  },
  {
    id: 7,
    code: CountryCode.ANGOLA,
    name: 'Angola',
    nameAr: 'أنجولا',
    phoneCode: '+244',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ao.svg',
    timeZones: [CountryTimezone.ANGOLA],
    offset: ['UTC +01:00'],
  },
  {
    id: 8,
    code: CountryCode.ANGUILLA,
    name: 'Anguilla',
    nameAr: 'أنجويلا',
    phoneCode: '+1-264',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ai.svg',
    timeZones: [CountryTimezone.ANGUILLA],
    offset: ['UTC -04:00'],
  },
  {
    id: 9,
    code: CountryCode.ANTARCTICA,
    name: 'Antarctica',
    nameAr: 'المنطقة القطبية الجنوبية',
    phoneCode: '+672',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/aq.svg',
    timeZones: [
      CountryTimezone.CASEY_TIME,
      CountryTimezone.DAVIS_TIME,
      CountryTimezone.DUMONTDURVILLE_TIME,
      CountryTimezone.MAWSON_TIME,
      CountryTimezone.ARGENTINA_TIME,
      CountryTimezone.GREENWICH_MEAN_TIME,
      CountryTimezone.CHILE_STANDARD_TIME,
      CountryTimezone.VOSTOK_TIME,
    ],
    offset: ['UTC +08:00', 'UTC +07:00', 'UTC +10:00', 'UTC +05:00', 'UTC -03:00', 'UTC +03:00', 'UTC', 'UTC +06:00'],
  },
  {
    id: 10,
    code: CountryCode.ANTIGUA_AND_BARBUDA,
    name: 'Antigua and Barbuda',
    nameAr: 'أنتيغوا وباربودا',
    phoneCode: '+1-268',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ag.svg',
    timeZones: [CountryTimezone.ANTIGUA_AND_BARBUDA],
    offset: ['UTC -04:00'],
  },
  {
    id: 11,
    code: CountryCode.ARGENTINA,
    name: 'Argentina',
    nameAr: 'الأرجنتين',
    phoneCode: '+54',
    phoneMinLength: 6,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ar.svg',
    timeZones: [CountryTimezone.ARGENTINA],
    offset: ['UTC -03:00'],
  },
  {
    id: 12,
    code: CountryCode.ARMENIA,
    name: 'Armenia',
    nameAr: 'أرمينيا',
    phoneCode: '+374',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/am.svg',
    timeZones: [CountryTimezone.ARMENIA],
    offset: ['UTC +04:00'],
  },
  {
    id: 13,
    code: CountryCode.ARUBA,
    name: 'Aruba',
    nameAr: 'اروبا',
    phoneCode: '+297',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/aw.svg',
    timeZones: [CountryTimezone.ARUBA],
    offset: ['UTC -04:00'],
  },
  {
    id: 14,
    code: CountryCode.AUSTRALIA,
    name: 'Australia',
    nameAr: 'أستراليا',
    phoneCode: '+61',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/au.svg',
    timeZones: [
      CountryTimezone.MACQUARIE,
      CountryTimezone.ADELAIDE,
      CountryTimezone.BRISBANE,
      CountryTimezone.BROKEN_HILL,
      CountryTimezone.CURRIE,
      CountryTimezone.DARWIN,
      CountryTimezone.EUCLA,
      CountryTimezone.HOBART,
      CountryTimezone.LINDEMAN,
      CountryTimezone.LORD_HOWE_ISLAND,
      CountryTimezone.MELBOURNE,
      CountryTimezone.PERTH,
      CountryTimezone.SYDNEY,
    ],
    offset: [
      'UTC +11:00',
      'UTC +10:30',
      'UTC +10:00',
      'UTC +10:30',
      'UTC +11:00',
      'UTC +09:30',
      'UTC +08:45',
      'UTC +11:00',
      'UTC +10:00',
      'UTC +11:00',
      'UTC +11:00',
      'UTC +08:00',
      'UTC +11:00',
    ],
  },
  {
    id: 15,
    code: CountryCode.AUSTRIA,
    name: 'Austria',
    nameAr: 'النمسا',
    phoneCode: '+43',
    phoneMinLength: 10,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/at.svg',
    timeZones: [CountryTimezone.AUSTRIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 16,
    code: CountryCode.AZERBAIJAN,
    name: 'Azerbaijan',
    nameAr: 'أذربيجان',
    phoneCode: '+994',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/az.svg',
    timeZones: [CountryTimezone.AZERBAIJAN],
    offset: ['UTC +04:00'],
  },
  {
    id: 17,
    code: CountryCode.BAHAMAS,
    name: 'Bahamas',
    nameAr: 'باهاماس',
    phoneCode: '+1-242',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/bs.svg',
    timeZones: [CountryTimezone.BAHAMAS],
    offset: ['UTC -05:00'],
  },
  {
    id: 18,
    code: CountryCode.BAHRAIN,
    name: 'Bahrain',
    nameAr: 'البحرين',
    phoneCode: '+973',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/bh.svg',
    timeZones: [CountryTimezone.BAHRAIN],
    offset: ['UTC +03:00'],
  },
  {
    id: 19,
    code: CountryCode.BANGLADESH,
    name: 'Bangladesh',
    nameAr: 'بنجلاديش',
    phoneCode: '+880',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/bd.svg',
    timeZones: [CountryTimezone.BANGLADESH],
    offset: ['UTC +06:00'],
  },
  {
    id: 20,
    code: CountryCode.BARBADOS,
    name: 'Barbados',
    nameAr: 'باربادوس',
    phoneCode: '+1-246',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/bb.svg',
    timeZones: [CountryTimezone.BARBADOS],
    offset: ['UTC -04:00'],
  },
  {
    id: 21,
    code: CountryCode.BELARUS,
    name: 'Belarus',
    nameAr: 'بيلاروس',
    phoneCode: '+375',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/by.svg',
    timeZones: [CountryTimezone.BELARUS],
    offset: ['UTC +03:00'],
  },
  {
    id: 22,
    code: CountryCode.BELGIUM,
    name: 'Belgium',
    nameAr: 'بلجيكا',
    phoneCode: '+32',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/be.svg',
    timeZones: [CountryTimezone.BELGIUM],
    offset: ['UTC +01:00'],
  },
  {
    id: 23,
    code: CountryCode.BELIZE,
    name: 'Belize',
    nameAr: 'بيليز',
    phoneCode: '+501',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/bz.svg',
    timeZones: [CountryTimezone.BELIZE],
    offset: ['UTC -06:00'],
  },
  {
    id: 24,
    code: CountryCode.BENIN,
    name: 'Benin',
    nameAr: 'بنين',
    phoneCode: '+229',
    phoneMinLength: 6,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/bj.svg',
    timeZones: [CountryTimezone.BENIN],
    offset: ['UTC +01:00'],
  },
  {
    id: 25,
    code: CountryCode.BERMUDA,
    name: 'Bermuda',
    nameAr: 'برمودا',
    phoneCode: '+1-441',
    phoneMinLength: 0,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/bm.svg',
    timeZones: [CountryTimezone.BERMUDA],
    offset: ['UTC -04:00'],
  },
  {
    id: 26,
    code: CountryCode.BHUTAN,
    name: 'Bhutan',
    nameAr: 'بوتان',
    phoneCode: '+975',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/bt.svg',
    timeZones: [CountryTimezone.BHUTAN],
    offset: ['UTC +06:00'],
  },
  {
    id: 27,
    code: CountryCode.BOLIVIA,
    name: 'Bolivia',
    nameAr: 'بوليفيا',
    phoneCode: '+591',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/bo.svg',
    timeZones: [CountryTimezone.BOLIVIA],
    offset: ['UTC -04:00'],
  },
  {
    id: 28,
    code: CountryCode.BONAIRE,
    name: 'Bonaire',
    nameAr: 'بونير',
    phoneCode: '+599',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/bq.svg',
    timeZones: [CountryTimezone.BONAIRE],
    offset: ['UTC -04:00'],
  },
  {
    id: 29,
    code: CountryCode.BOSNIA_AND_HERZEGOVINA,
    name: 'Bosnia and Herzegovina',
    nameAr: 'البوسنة والهرسك',
    phoneCode: '+387',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ba.svg',
    timeZones: [CountryTimezone.BOSNIA_AND_HERZEGOVINA],
    offset: ['UTC +01:00'],
  },
  {
    id: 30,
    code: CountryCode.BOTSWANA,
    name: 'Botswana',
    nameAr: 'بوتسوانا',
    phoneCode: '+267',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/bw.svg',
    timeZones: [CountryTimezone.BOTSWANA],
    offset: ['UTC +02:00'],
  },
  {
    id: 31,
    code: CountryCode.BRAZIL,
    name: 'Brazil',
    nameAr: 'البرازيل',
    phoneCode: '+55',
    phoneMinLength: 11,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/br.svg',
    timeZones: [
      CountryTimezone.ARAGUAINA,
      CountryTimezone.BAHIA,
      CountryTimezone.BELEM,
      CountryTimezone.BOA_VISTA,
      CountryTimezone.CAMPO_GRANDE,
      CountryTimezone.CUIABA,
      CountryTimezone.EIRUNEPE,
      CountryTimezone.FORTALEZA,
      CountryTimezone.MACEIO,
      CountryTimezone.AMAZON_TIME,
      CountryTimezone.FERNANDO_DE_NORONHA_TIME,
      CountryTimezone.PORTO_VELHO,
      CountryTimezone.RECIFE,
      CountryTimezone.ACRE_TIME,
      CountryTimezone.SANTAREM,
      CountryTimezone.BRASILIA_TIME,
    ],
    offset: [
      'UTC -03:00',
      'UTC -03:00',
      'UTC -03:00',
      'UTC -04:00',
      'UTC -03:00',
      'UTC -03:00',
      'UTC -05:00',
      'UTC -03:00',
      'UTC -03:00',
      'UTC -04:00',
      'UTC -02:00',
      'UTC -04:00',
      'UTC -03:00',
      'UTC -05:00',
      'UTC -03:00',
      'UTC -02:00',
    ],
  },
  {
    id: 32,
    code: CountryCode.BRITISH_INDIAN_OCEAN_TERRITORY,
    name: 'British Indian Ocean Territory',
    nameAr: 'إقليم المحيط الهندي البريطاني',
    phoneCode: '+246',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/io.svg',
    timeZones: [CountryTimezone.BRITISH_INDIAN_OCEAN_TERRITORY],
    offset: ['UTC +06:00'],
  },
  {
    id: 33,
    code: CountryCode.BRITISH_VIRGIN_ISLANDS,
    name: 'British Virgin Islands',
    nameAr: 'جزر العذراء البريطانية',
    phoneCode: '+1-284',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/vg.svg',
    timeZones: [CountryTimezone.BRITISH_VIRGIN_ISLANDS],
    offset: ['UTC -04:00'],
  },
  {
    id: 34,
    code: CountryCode.BRUNEI,
    name: 'Brunei',
    nameAr: 'بروناي',
    phoneCode: '+673',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/bn.svg',
    timeZones: [CountryTimezone.BRUNEI],
    offset: ['UTC +08:00'],
  },
  {
    id: 35,
    code: CountryCode.BULGARIA,
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    phoneCode: '+359',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/bg.svg',
    timeZones: [CountryTimezone.BULGARIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 36,
    code: CountryCode.BURKINA_FASO,
    name: 'Burkina Faso',
    nameAr: 'بوركينا فاسو',
    phoneCode: '+226',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/bf.svg',
    timeZones: [CountryTimezone.BURKINA_FASO],
    offset: ['UTC'],
  },
  {
    id: 37,
    code: CountryCode.BURUNDI,
    name: 'Burundi',
    nameAr: 'بوروندي',
    phoneCode: '+257',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/bi.svg',
    timeZones: [CountryTimezone.BURUNDI],
    offset: ['UTC +02:00'],
  },
  {
    id: 38,
    code: CountryCode.CAMBODIA,
    name: 'Cambodia',
    nameAr: 'كمبوديا',
    phoneCode: '+855',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/kh.svg',
    timeZones: [CountryTimezone.CAMBODIA],
    offset: ['UTC +07:00'],
  },
  {
    id: 39,
    code: CountryCode.CAMEROON,
    name: 'Cameroon',
    nameAr: 'الكاميرون',
    phoneCode: '+237',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/cm.svg',
    timeZones: [CountryTimezone.CAMEROON],
    offset: ['UTC +01:00'],
  },
  {
    id: 40,
    code: CountryCode.CANADA,
    name: 'Canada',
    nameAr: 'كندا',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ca.svg',
    timeZones: [
      // CountryTimezone.undefined,'America/Atikokan',
      // CountryTimezone.undefined,'America/Blanc-Sablon',
      // CountryTimezone.undefined,'America/Cambridge_Bay',
      // CountryTimezone.undefined,'America/Creston',
      // CountryTimezone.undefined,'America/Dawson',
      // CountryTimezone.undefined,'America/Dawson_Creek',
      // CountryTimezone.EDMONTON_MOUNTAIN_STANDARD_TIME,'America/Edmonton',
      // CountryTimezone.undefined,'America/Fort_Nelson',
      // CountryTimezone.undefined,'America/Glace_Bay',
      // CountryTimezone.undefined,'America/Goose_Bay',
      // CountryTimezone.ATLANTIC_STANDARD_TIME,'America/Halifax',
      // CountryTimezone.undefined,'America/Inuvik',
      // CountryTimezone.undefined,'America/Iqaluit',
      // CountryTimezone.undefined,'America/Moncton',
      // CountryTimezone.undefined,'America/Nipigon',
      // CountryTimezone.undefined,'America/Pangnirtung',
      // CountryTimezone.undefined,'America/Rainy_River',
      // CountryTimezone.undefined,'America/Rankin_Inlet',
      // CountryTimezone.undefined,'America/Regina',
      // CountryTimezone.undefined,'America/Resolute',
      // CountryTimezone.NEWFOUNDLAND_STANDARD_TIME,'America/St_Johns',
      // CountryTimezone.undefined,'America/Swift_Current',
      // CountryTimezone.undefined,'America/Thunder_Bay',
      // CountryTimezone.TORONTO_EASTERN_STANDARD_TIME,'America/Toronto',
      // CountryTimezone.VANCOUVER_PACIFIC_STANDARD_TIME,'America/Vancouver',
      // CountryTimezone.undefined,'America/Whitehorse',
      // CountryTimezone.WINNIPEG_CENTRAL_STANDARD_TIME,'America/Winnipeg',
      // CountryTimezone.undefined,'America/Yellowknife',
    ],
    offset: [
      'UTC -05:00',
      'UTC -04:00',
      'UTC -07:00',
      'UTC -07:00',
      'UTC -08:00',
      'UTC -07:00',
      'UTC -07:00',
      'UTC -07:00',
      'UTC -04:00',
      'UTC -04:00',
      'UTC -04:00',
      'UTC -07:00',
      'UTC -05:00',
      'UTC -04:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -06:00',
      'UTC -06:00',
      'UTC -06:00',
      'UTC -06:00',
      'UTC -03:30',
      'UTC -06:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -08:00',
      'UTC -08:00',
      'UTC -06:00',
      'UTC -07:00',
    ],
  },
  {
    id: 41,
    code: CountryCode.CAPE_VERDE,
    name: 'Cape Verde',
    nameAr: 'الرأس الأخضر',
    phoneCode: '+238',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/cv.svg',
    timeZones: [CountryTimezone.CAPE_VERDE],
    offset: ['UTC -01:00'],
  },
  {
    id: 42,
    code: CountryCode.CAYMAN_ISLANDS,
    name: 'Cayman Islands',
    nameAr: 'جزر كايمان',
    phoneCode: '+1-345',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ky.svg',
    timeZones: [CountryTimezone.CAYMAN_ISLANDS],
    offset: ['UTC -05:00'],
  },
  {
    id: 43,
    code: CountryCode.CENTRAL_AFRICAN_REPUBLIC,
    name: 'Central African Republic',
    nameAr: 'جمهورية أفريقيا الوسطى',
    phoneCode: '+236',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/cf.svg',
    timeZones: [CountryTimezone.CENTRAL_AFRICAN_REPUBLIC],
    offset: ['UTC +01:00'],
  },
  {
    id: 44,
    code: CountryCode.CHAD,
    name: 'Chad',
    nameAr: 'تشاد',
    phoneCode: '+235',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/td.svg',
    timeZones: [CountryTimezone.CHAD],
    offset: ['UTC +01:00'],
  },
  {
    id: 45,
    code: CountryCode.CHILE,
    name: 'Chile',
    nameAr: 'تشيلي',
    phoneCode: '+56',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/cl.svg',
    timeZones: [CountryTimezone.CHILE_STANDARD_TIME_AMERICA, CountryTimezone.EASTER_ISLAND_STANDARD_TIME],
    offset: ['UTC -03:00', 'UTC -05:00'],
  },
  {
    id: 46,
    code: CountryCode.CHINA,
    name: 'China',
    nameAr: 'الصين',
    phoneCode: '+86',
    phoneMinLength: 11,
    phoneMaxLength: 13,
    flag: 'assets/countries-flag/svg/cn.svg',
    timeZones: [CountryTimezone.CHINA, CountryTimezone.URUMQI],
    offset: ['UTC +08:00', 'UTC +06:00'],
  },
  {
    id: 47,
    code: CountryCode.CHRISTMAS_ISLAND,
    name: 'Christmas Island',
    nameAr: 'جزيرة كريسماس',
    phoneCode: '+61',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/cx.svg',
    timeZones: [CountryTimezone.CHRISTMAS_ISLAND],
    offset: ['UTC +07:00'],
  },
  {
    id: 48,
    code: CountryCode.COCOS_ISLANDS,
    name: 'Cocos Islands',
    nameAr: 'جزر كوكوس',
    phoneCode: '+61',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/cc.svg',
    timeZones: [CountryTimezone.COCOS_ISLANDS],
    offset: ['UTC +06:30'],
  },
  {
    id: 49,
    code: CountryCode.COLOMBIA,
    name: 'Colombia',
    nameAr: 'كولومبيا',
    phoneCode: '+57',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/co.svg',
    timeZones: [CountryTimezone.COLOMBIA],
    offset: ['UTC -05:00'],
  },
  {
    id: 50,
    code: CountryCode.COMOROS,
    name: 'Comoros',
    nameAr: 'جزر القمر',
    phoneCode: '+269',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/km.svg',
    timeZones: [CountryTimezone.COMOROS],
    offset: ['UTC +03:00'],
  },
  {
    id: 51,
    code: CountryCode.COOK_ISLANDS,
    name: 'Cook Islands',
    nameAr: 'جزر كوك',
    phoneCode: '+682',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/ck.svg',
    timeZones: [CountryTimezone.COOK_ISLANDS],
    offset: ['UTC -10:00'],
  },
  {
    id: 52,
    code: CountryCode.COSTA_RICA,
    name: 'Costa Rica',
    nameAr: 'كوستاريكا',
    phoneCode: '+506',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/cr.svg',
    timeZones: [CountryTimezone.COSTA_RICA],
    offset: ['UTC -06:00'],
  },
  {
    id: 53,
    code: CountryCode.CROATIA,
    name: 'Croatia',
    nameAr: 'كرواتيا',
    phoneCode: '+385',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/hr.svg',
    timeZones: [CountryTimezone.CROATIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 54,
    code: CountryCode.CUBA,
    name: 'Cuba',
    nameAr: 'كوبا',
    phoneCode: '+53',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/cu.svg',
    timeZones: [CountryTimezone.CUBA],
    offset: ['UTC -05:00'],
  },
  {
    id: 55,
    code: CountryCode.CURAÇAO,
    name: 'Curaçao',
    nameAr: 'كوراساو',
    phoneCode: '+599',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/cw.svg',
    timeZones: [CountryTimezone.CURACAO],
    offset: ['UTC -04:00'],
  },
  {
    id: 56,
    code: CountryCode.CYPRUS,
    name: 'Cyprus',
    nameAr: 'قبرص',
    phoneCode: '+357',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/cy.svg',
    timeZones: [CountryTimezone.FAMAGUSTA, CountryTimezone.CYPRUS],
    offset: ['UTC +02:00', 'UTC +02:00'],
  },
  {
    id: 57,
    code: CountryCode.CZECH_REPUBLIC,
    name: 'Czech Republic',
    nameAr: 'التشيك',
    phoneCode: '+420',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/cz.svg',
    timeZones: [CountryTimezone.CZECH_REPUBLIC],
    offset: ['UTC +01:00'],
  },
  {
    id: 58,
    code: CountryCode.DEMOCRATIC_REPUBLIC_OF_THE_CONGO,
    name: 'Democratic Republic of the Congo',
    nameAr: 'جمهورية الكونغو الديمقراطية',
    phoneCode: '+243',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/cd.svg',
    timeZones: [CountryTimezone.WEST_AFRICA_TIME, CountryTimezone.CENTRAL_AFRICA_TIME],
    offset: ['UTC +01:00', 'UTC +02:00'],
  },
  {
    id: 59,
    code: CountryCode.DENMARK,
    name: 'Denmark',
    nameAr: 'الدنمارك',
    phoneCode: '+45',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/dk.svg',
    timeZones: [CountryTimezone.DENMARK],
    offset: ['UTC +01:00'],
  },
  {
    id: 60,
    code: CountryCode.DJIBOUTI,
    name: 'Djibouti',
    nameAr: 'جيبوتي',
    phoneCode: '+253',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/dj.svg',
    timeZones: [CountryTimezone.DJIBOUTI],
    offset: ['UTC +03:00'],
  },
  {
    id: 61,
    code: CountryCode.DOMINICA,
    name: 'Dominica',
    nameAr: 'دومينيكا',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/dm.svg',
    timeZones: [CountryTimezone.DOMINICA],
    offset: ['UTC -04:00'],
  },
  {
    id: 62,
    code: CountryCode.DOMINICAN_REPUBLIC,
    name: 'Dominican Republic',
    nameAr: 'جمهورية الدومينيكان',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/do.svg',
    timeZones: [CountryTimezone.DOMINICAN_REPUBLIC],
    offset: ['UTC -04:00'],
  },
  {
    id: 63,
    code: CountryCode.EAST_TIMOR,
    name: 'East Timor',
    nameAr: 'تيمور الشرقية',
    phoneCode: '+670',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/tl.svg',
    timeZones: [CountryTimezone.TIMOR_LESTE],
    offset: ['UTC +09:00'],
  },
  {
    id: 64,
    code: CountryCode.ECUADOR,
    name: 'Ecuador',
    nameAr: 'الإكوادور',
    phoneCode: '+593',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ec.svg',
    timeZones: [CountryTimezone.ECUADOR_GUAYAQUIL_TIME, CountryTimezone.ECUADOR_GALAPAGOS_TIME],
    offset: ['UTC -05:00', 'UTC -06:00'],
  },
  {
    id: 65,
    code: CountryCode.EGYPT,
    name: 'Egypt',
    nameAr: 'مصر',
    phoneCode: '+20',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/eg.svg',
    timeZones: [CountryTimezone.EGYPT],
    offset: ['UTC +02:00'],
  },
  {
    id: 66,
    code: CountryCode.EL_SALVADOR,
    name: 'El Salvador',
    nameAr: 'السلفادور',
    phoneCode: '+503',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/sv.svg',
    timeZones: [CountryTimezone.EL_SALVADOR],
    offset: ['UTC -06:00'],
  },
  {
    id: 67,
    code: CountryCode.EQUATORIAL_GUINEA,
    name: 'Equatorial Guinea',
    nameAr: 'غينيا الاستوائية',
    phoneCode: '+240',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/gq.svg',
    timeZones: [CountryTimezone.EQUATORIAL_GUINEA],
    offset: ['UTC +01:00'],
  },
  {
    id: 68,
    code: CountryCode.ERITREA,
    name: 'Eritrea',
    nameAr: 'إريتريا',
    phoneCode: '+291',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/er.svg',
    timeZones: [CountryTimezone.ERITREA],
    offset: ['UTC +03:00'],
  },
  {
    id: 69,
    code: CountryCode.ESTONIA,
    name: 'Estonia',
    nameAr: 'إستونيا',
    phoneCode: '+372',
    phoneMinLength: 7,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ee.svg',
    timeZones: [CountryTimezone.ESTONIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 70,
    code: CountryCode.ETHIOPIA,
    name: 'Ethiopia',
    nameAr: 'إثيوبيا',
    phoneCode: '+251',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/et.svg',
    timeZones: [CountryTimezone.ETHIOPIA],
    offset: ['UTC +03:00'],
  },
  {
    id: 71,
    code: CountryCode.FALKLAND_ISLANDS,
    name: 'Falkland Islands',
    nameAr: 'جزر فوكلاند',
    phoneCode: '+500',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/fk.svg',
    timeZones: [CountryTimezone.FALKLAND_ISLANDS],
    offset: ['UTC -03:00'],
  },
  {
    id: 72,
    code: CountryCode.FAROE_ISLANDS,
    name: 'Faroe Islands',
    nameAr: 'جزر فارو',
    phoneCode: '+298',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/fo.svg',
    timeZones: [CountryTimezone.FAROE_ISLANDS],
    offset: ['UTC'],
  },
  {
    id: 73,
    code: CountryCode.FIJI,
    name: 'Fiji',
    nameAr: 'فيجي',
    phoneCode: '+679',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/fj.svg',
    timeZones: [CountryTimezone.FIJI],
    offset: ['UTC +13:00'],
  },
  {
    id: 74,
    code: CountryCode.FINLAND,
    name: 'Finland',
    nameAr: 'فنلندا',
    phoneCode: '+358',
    phoneMinLength: 8,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/fi.svg',
    timeZones: [CountryTimezone.FINLAND],
    offset: ['UTC +02:00'],
  },
  {
    id: 75,
    code: CountryCode.FRANCE,
    name: 'France',
    nameAr: 'فرنسا',
    phoneCode: '+33',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/fr.svg',
    timeZones: [CountryTimezone.FRANCE],
    offset: ['UTC +01:00'],
  },
  {
    id: 76,
    code: CountryCode.FRENCH_GUIANA,
    name: 'French Guiana',
    nameAr: 'غينيا الفرنسية',
    phoneCode: '+594',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/gf.svg',
    timeZones: [CountryTimezone.FRENCH_GUIANA],
    offset: ['UTC -03:00'],
  },
  {
    id: 77,
    code: CountryCode.FRENCH_POLYNESIA,
    name: 'French Polynesia',
    nameAr: 'بولينيزيا الفرنسية',
    phoneCode: '+689',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/pf.svg',
    timeZones: [CountryTimezone.GAMBIER_TIME, CountryTimezone.MARQUESAS_TIME, CountryTimezone.TAHITI_TIME],
    offset: ['UTC -09:00', 'UTC -09:30', 'UTC -10:00'],
  },
  {
    id: 78,
    code: CountryCode.FRENCH_SOUTHERN_TERRITORIES,
    name: 'French Southern Territories',
    nameAr: 'الأراضي الجنوبية الفرنسية',
    phoneCode: '+262',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/tf.svg',
    timeZones: [CountryTimezone.FRENCH_SOUTHERN_TERRITORIES],
    offset: ['UTC +05:00'],
  },
  {
    id: 79,
    code: CountryCode.GABON,
    name: 'Gabon',
    nameAr: 'الغابون',
    phoneCode: '+241',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/ga.svg',
    timeZones: [CountryTimezone.GABON],
    offset: ['UTC +01:00'],
  },
  {
    id: 80,
    code: CountryCode.GAMBIA,
    name: 'Gambia',
    nameAr: 'غامبيا',
    phoneCode: '+220',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/gm.svg',
    timeZones: [CountryTimezone.GAMBIA],
    offset: ['UTC'],
  },
  {
    id: 81,
    code: CountryCode.GEORGIA,
    name: 'Georgia',
    nameAr: 'جورجيا',
    phoneCode: '+995',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ge.svg',
    timeZones: [CountryTimezone.GEORGIA],
    offset: ['UTC +04:00'],
  },
  {
    id: 82,
    code: CountryCode.GERMANY,
    name: 'Germany',
    nameAr: 'ألمانيا',
    phoneCode: '+49',
    phoneMinLength: 10,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/de.svg',
    timeZones: [CountryTimezone.GERMANY, CountryTimezone.BUSINGEN],
    offset: ['UTC +01:00', 'UTC +01:00'],
  },
  {
    id: 83,
    code: CountryCode.GHANA,
    name: 'Ghana',
    nameAr: 'غانا',
    phoneCode: '+233',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/gh.svg',
    timeZones: [CountryTimezone.GHANA],
    offset: ['UTC'],
  },
  {
    id: 84,
    code: CountryCode.GIBRALTAR,
    name: 'Gibraltar',
    nameAr: 'جيبرالتار',
    phoneCode: '+350',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/gi.svg',
    timeZones: [CountryTimezone.GIBRALTAR],
    offset: ['UTC +01:00'],
  },
  {
    id: 85,
    code: CountryCode.GREECE,
    name: 'Greece',
    nameAr: 'اليونان',
    phoneCode: '+30',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/gr.svg',
    timeZones: [CountryTimezone.GREECE],
    offset: ['UTC +02:00'],
  },
  {
    id: 86,
    code: CountryCode.GREENLAND,
    name: 'Greenland',
    nameAr: 'جرينلاند',
    phoneCode: '+299',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/gl.svg',
    timeZones: [
      CountryTimezone.GREENWICH_MEAN_TIME_AMERICA,
      CountryTimezone.WEST_GREENLAND_TIME,
      CountryTimezone.EAST_GREENLAND_TIME,
      CountryTimezone.ATLANTIC_STANDARD_TIME_THULE,
    ],
    offset: ['UTC', 'UTC -03:00', 'UTC -01:00', 'UTC -04:00'],
  },
  {
    id: 87,
    code: CountryCode.GRENADA,
    name: 'Grenada',
    nameAr: 'غرينادا',
    phoneCode: '+1-473',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/gd.svg',
    timeZones: [CountryTimezone.GRENADA],
    offset: ['UTC -04:00'],
  },
  {
    id: 88,
    code: CountryCode.GUADELOUPE,
    name: 'Guadeloupe',
    nameAr: 'غوادلوب',
    phoneCode: '+590',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/gp.svg',
    timeZones: [CountryTimezone.GUADELOUPE],
    offset: ['UTC -04:00'],
  },
  {
    id: 89,
    code: CountryCode.GUAM,
    name: 'Guam',
    nameAr: 'غوام',
    phoneCode: '+1-671',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/gu.svg',
    timeZones: [CountryTimezone.GUAM],
    offset: ['UTC +10:00'],
  },
  {
    id: 90,
    code: CountryCode.GUATEMALA,
    name: 'Guatemala',
    nameAr: 'غواتيمال',
    phoneCode: '+502',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/gt.svg',
    timeZones: [CountryTimezone.GUATEMALA],
    offset: ['UTC -06:00'],
  },
  {
    id: 91,
    code: CountryCode.GUERNSEY,
    name: 'Guernsey',
    nameAr: 'جيرنزى',
    phoneCode: '+44-1481',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/gg.svg',
    timeZones: [CountryTimezone.GUERNSEY],
    offset: ['UTC'],
  },
  {
    id: 92,
    code: CountryCode.GUINEA,
    name: 'Guinea',
    nameAr: 'غينيا',
    phoneCode: '+224',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/gn.svg',
    timeZones: [CountryTimezone.GUINEA],
    offset: ['UTC'],
  },
  {
    id: 93,
    code: CountryCode.GUINEA_BISSAU,
    name: 'Guinea-Bissau',
    nameAr: 'غينيا بيساو',
    phoneCode: '+245',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/gw.svg',
    timeZones: [CountryTimezone.GUINEA_BISSAU],
    offset: ['UTC'],
  },
  {
    id: 94,
    code: CountryCode.GUYANA,
    name: 'Guyana',
    nameAr: 'غيانا',
    phoneCode: '+592',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/gy.svg',
    timeZones: [CountryTimezone.GUYANA],
    offset: ['UTC -04:00'],
  },
  {
    id: 95,
    code: CountryCode.HAITI,
    name: 'Haiti',
    nameAr: 'هايتي',
    phoneCode: '+509',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ht.svg',
    timeZones: [CountryTimezone.HAITI],
    offset: ['UTC -05:00'],
  },
  {
    id: 96,
    code: CountryCode.HONDURAS,
    name: 'Honduras',
    nameAr: 'هندوراس',
    phoneCode: '+504',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/hn.svg',
    timeZones: [CountryTimezone.HONDURAS],
    offset: ['UTC -06:00'],
  },
  {
    id: 97,
    code: CountryCode.HONG_KONG,
    name: 'Hong Kong',
    nameAr: 'هونغ كونغ',
    phoneCode: '+852',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/hk.svg',
    timeZones: [CountryTimezone.HONG_KONG],
    offset: ['UTC +08:00'],
  },
  {
    id: 98,
    code: CountryCode.HUNGARY,
    name: 'Hungary',
    nameAr: 'المجر',
    phoneCode: '+36',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/hu.svg',
    timeZones: [CountryTimezone.HUNGARY],
    offset: ['UTC +01:00'],
  },
  {
    id: 99,
    code: CountryCode.ICELAND,
    name: 'Iceland',
    nameAr: 'أيسلندا',
    phoneCode: '+354',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/is.svg',
    timeZones: [CountryTimezone.ICELAND],
    offset: ['UTC'],
  },
  {
    id: 100,
    code: CountryCode.INDIA,
    name: 'India',
    nameAr: 'الهند',
    phoneCode: '+91',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/in.svg',
    timeZones: [CountryTimezone.INDIA],
    offset: ['UTC +05:30'],
  },
  {
    id: 101,
    code: CountryCode.INDONESIA,
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    phoneCode: '+62',
    phoneMinLength: 9,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/id.svg',
    timeZones: [
      CountryTimezone.WESTERN_INDONESIAN_TIME,
      CountryTimezone.EASTERN_INDONESIAN_TIME,
      CountryTimezone.CENTRAL_INDONESIAN_TIME,
      CountryTimezone.PONTIANAK,
    ],
    offset: ['UTC +07:00', 'UTC +09:00', 'UTC +08:00', 'UTC +07:00'],
  },
  {
    id: 102,
    code: CountryCode.IRAN,
    name: 'Iran',
    nameAr: 'إيران',
    phoneCode: '+98',
    phoneMinLength: 10,
    phoneMaxLength: 11,
    flag: 'assets/countries-flag/svg/ir.svg',
    timeZones: [CountryTimezone.IRAN],
    offset: ['UTC +03:30'],
  },
  {
    id: 103,
    code: CountryCode.IRAQ,
    name: 'Iraq',
    nameAr: 'العراق',
    phoneCode: '+964',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/iq.svg',
    timeZones: [CountryTimezone.IRAQ],
    offset: ['UTC +03:00'],
  },
  {
    id: 104,
    code: CountryCode.IRELAND,
    name: 'Ireland',
    nameAr: 'جمهورية أيرلندا',
    phoneCode: '+353',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ie.svg',
    timeZones: [CountryTimezone.IRELAND],
    offset: ['UTC'],
  },
  {
    id: 105,
    code: CountryCode.ISLE_OF_MAN,
    name: 'Isle of Man',
    nameAr: 'جزيرة مان',
    phoneCode: '+44-1624',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/im.svg',
    timeZones: [CountryTimezone.ISLE_OF_MAN],
    offset: ['UTC'],
  },
  {
    id: 106,
    code: CountryCode.PALESTINIAN_TERRITORY,
    name: 'Occupied Palestine',
    nameAr: 'فلسطين المحتلة',
    phoneCode: '+972',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ps.svg',
    timeZones: [CountryTimezone.PALESTINE],
    offset: ['UTC +02:00'],
  },
  {
    id: 107,
    code: CountryCode.ITALY,
    name: 'Italy',
    nameAr: 'إيطاليا',
    phoneCode: '+39',
    phoneMinLength: 9,
    phoneMaxLength: 13,
    flag: 'assets/countries-flag/svg/it.svg',
    timeZones: [CountryTimezone.ITALY],
    offset: ['UTC +01:00'],
  },
  {
    id: 108,
    code: CountryCode.IVORY_COAST,
    name: 'Ivory Coast',
    nameAr: 'ساحل العاج',
    phoneCode: '+225',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ci.svg',
    timeZones: [CountryTimezone.IVORY_COAST],
    offset: ['UTC'],
  },
  {
    id: 109,
    code: CountryCode.JAMAICA,
    name: 'Jamaica',
    nameAr: 'جامايكا',
    phoneCode: '+1-876',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/jm.svg',
    timeZones: [CountryTimezone.JAMAICA],
    offset: ['UTC -05:00'],
  },
  {
    id: 110,
    code: CountryCode.JAPAN,
    name: 'Japan',
    nameAr: 'اليابان',
    phoneCode: '+81',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/jp.svg',
    timeZones: [CountryTimezone.JAPAN],
    offset: ['UTC +09:00'],
  },
  {
    id: 111,
    code: CountryCode.JERSEY,
    name: 'Jersey',
    nameAr: 'جيرسى',
    phoneCode: '+44-1534',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/je.svg',
    timeZones: [CountryTimezone.JERSEY],
    offset: ['UTC'],
  },
  {
    id: 112,
    code: CountryCode.JORDAN,
    name: 'Jordan',
    nameAr: 'الأردن',
    phoneCode: '+962',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/jo.svg',
    timeZones: [CountryTimezone.JORDAN],
    offset: ['UTC +02:00'],
  },
  {
    id: 113,
    code: CountryCode.KAZAKHSTAN,
    name: 'Kazakhstan',
    nameAr: 'كازاخستان',
    phoneCode: '+7',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/kz.svg',
    timeZones: [
      CountryTimezone.ALMA_ATA_TIME,
      CountryTimezone.AQTAU,
      CountryTimezone.AQTOBE_TIME,
      CountryTimezone.ATYRAU,
      CountryTimezone.ORAL_TIME,
      CountryTimezone.QYZYLORDA,
    ],
    offset: ['UTC +06:00', 'UTC +05:00', 'UTC +05:00', 'UTC +05:00', 'UTC +05:00', 'UTC +06:00'],
  },
  {
    id: 114,
    code: CountryCode.KENYA,
    name: 'Kenya',
    nameAr: 'كينيا',
    phoneCode: '+254',
    phoneMinLength: 9,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ke.svg',
    timeZones: [CountryTimezone.KENYA],
    offset: ['UTC +03:00'],
  },
  {
    id: 115,
    code: CountryCode.KIRIBATI,
    name: 'Kiribati',
    nameAr: 'كيريباتي',
    phoneCode: '+686',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ki.svg',
    timeZones: [CountryTimezone.PHOENIX_ISLAND_TIME, CountryTimezone.LINE_ISLANDS_TIME, CountryTimezone.GILBERT_ISLAND_TIME],
    offset: ['UTC +13:00', 'UTC +14:00', 'UTC +12:00'],
  },
  {
    id: 116,
    code: CountryCode.KUWAIT,
    name: 'Kuwait',
    nameAr: 'الكويت',
    phoneCode: '+965',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/kw.svg',
    timeZones: [CountryTimezone.KUWAIT],
    offset: ['UTC +03:00'],
  },
  {
    id: 117,
    code: CountryCode.KYRGYZSTAN,
    name: 'Kyrgyzstan',
    nameAr: 'قيرغيزستان',
    phoneCode: '+966',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/kg.svg',
    timeZones: [CountryTimezone.KYRGYZSTAN],
    offset: ['UTC +06:00'],
  },
  {
    id: 118,
    code: CountryCode.LAOS,
    name: 'Laos',
    nameAr: 'لاوس',
    phoneCode: '+856',
    phoneMinLength: 8,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/la.svg',
    timeZones: [CountryTimezone.LAOS],
    offset: ['UTC +07:00'],
  },
  {
    id: 119,
    code: CountryCode.LATVIA,
    name: 'Latvia',
    nameAr: 'لاتفيا',
    phoneCode: '+371',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/lv.svg',
    timeZones: [CountryTimezone.LATVIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 120,
    code: CountryCode.LEBANON,
    name: 'Lebanon',
    nameAr: 'لبنان',
    phoneCode: '+961',
    phoneMinLength: 7,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/lb.svg',
    timeZones: [CountryTimezone.LEBANON],
    offset: ['UTC +02:00'],
  },
  {
    id: 121,
    code: CountryCode.LESOTHO,
    name: 'Lesotho',
    nameAr: 'ليسوتو',
    phoneCode: '+266',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ls.svg',
    timeZones: [CountryTimezone.LESOTHO],
    offset: ['UTC +02:00'],
  },
  {
    id: 122,
    code: CountryCode.LIBERIA,
    name: 'Liberia',
    nameAr: 'ليبيريا',
    phoneCode: '+231',
    phoneMinLength: 7,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/lr.svg',
    timeZones: [CountryTimezone.LIBERIA],
    offset: ['UTC'],
  },
  {
    id: 123,
    code: CountryCode.LIBYA,
    name: 'Libya',
    nameAr: 'ليبيا',
    phoneCode: '+218',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ly.svg',
    timeZones: [CountryTimezone.LIBYA],
    offset: ['UTC +02:00'],
  },
  {
    id: 124,
    code: CountryCode.LIECHTENSTEIN,
    name: 'Liechtenstein',
    nameAr: 'ليختنشتاين',
    phoneCode: '+423',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/li.svg',
    timeZones: [CountryTimezone.LIECHTENSTEIN],
    offset: ['UTC +01:00'],
  },
  {
    id: 125,
    code: CountryCode.LITHUANIA,
    name: 'Lithuania',
    nameAr: 'ليتوانيا',
    phoneCode: '+370',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/lt.svg',
    timeZones: [CountryTimezone.LITHUANIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 126,
    code: CountryCode.LUXEMBOURG,
    name: 'Luxembourg',
    nameAr: 'لوكسمبورغ',
    phoneCode: '+352',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/lu.svg',
    timeZones: [CountryTimezone.LUXEMBOURG],
    offset: ['UTC +01:00'],
  },
  {
    id: 127,
    code: CountryCode.MACAO,
    name: 'Macau',
    nameAr: 'ماكاو',
    phoneCode: '+853',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mo.svg',
    timeZones: [CountryTimezone.MACAU],
    offset: ['UTC +08:00'],
  },
  {
    id: 128,
    code: CountryCode.MACEDONIA,
    name: 'Macedonia',
    nameAr: 'مقدونيا الشمالية',
    phoneCode: '+389',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mk.svg',
    timeZones: [CountryTimezone.MACEDONIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 129,
    code: CountryCode.MADAGASCAR,
    name: 'Madagascar',
    nameAr: 'مدغشقر',
    phoneCode: '+261',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/mg.svg',
    timeZones: [CountryTimezone.MADAGASCAR],
    offset: ['UTC +03:00'],
  },
  {
    id: 130,
    code: CountryCode.MALAWI,
    name: 'Malawi',
    nameAr: 'مالاوي',
    phoneCode: '+265',
    phoneMinLength: 7,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/mw.svg',
    timeZones: [CountryTimezone.MALAWI],
    offset: ['UTC +02:00'],
  },
  {
    id: 131,
    code: CountryCode.MALAYSIA,
    name: 'Malaysia',
    nameAr: 'ماليزيا',
    phoneCode: '+60',
    phoneMinLength: 8,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/my.svg',
    timeZones: [CountryTimezone.MALAYSIA, CountryTimezone.KUCHING],
    offset: ['UTC +08:00', 'UTC +08:00'],
  },
  {
    id: 132,
    code: CountryCode.MALDIVES,
    name: 'Maldives',
    nameAr: 'المالديف',
    phoneCode: '+960',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/mv.svg',
    timeZones: [CountryTimezone.MALDIVES],
    offset: ['UTC +05:00'],
  },
  {
    id: 133,
    code: CountryCode.MALI,
    name: 'Mali',
    nameAr: 'مالى',
    phoneCode: '+223',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ml.svg',
    timeZones: [CountryTimezone.MALI],
    offset: ['UTC'],
  },
  {
    id: 134,
    code: CountryCode.MALTA,
    name: 'Malta',
    nameAr: 'مالطه',
    phoneCode: '+356',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mt.svg',
    timeZones: [CountryTimezone.MALTA],
    offset: ['UTC +01:00'],
  },
  {
    id: 135,
    code: CountryCode.MARSHALL_ISLANDS,
    name: 'Marshall Islands',
    nameAr: 'جزر مارشال',
    phoneCode: '+692',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/mh.svg',
    timeZones: [CountryTimezone.MARSHALL_ISLANDS],
    offset: ['UTC +12:00'],
  },
  {
    id: 136,
    code: CountryCode.MARTINIQUE,
    name: 'Martinique',
    nameAr: 'مارتينيك',
    phoneCode: '+596',
    phoneMinLength: 9,
    phoneMaxLength: 12,
    flag: 'assets/countries-flag/svg/mq.svg',
    timeZones: [CountryTimezone.MARTINIQUE],
    offset: ['UTC -04:00'],
  },
  {
    id: 137,
    code: CountryCode.MAURITANIA,
    name: 'Mauritania',
    nameAr: 'موريتانيا',
    phoneCode: '+222',
    phoneMinLength: 6,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mr.svg',
    timeZones: [CountryTimezone.MAURITANIA],
    offset: ['UTC'],
  },
  {
    id: 138,
    code: CountryCode.MAURITIUS,
    name: 'Mauritius',
    nameAr: 'موريشيوس',
    phoneCode: '+230',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mu.svg',
    timeZones: [CountryTimezone.MAURITIUS],
    offset: ['UTC +04:00'],
  },
  {
    id: 139,
    code: CountryCode.MAYOTTE,
    name: 'Mayotte',
    nameAr: 'مايوت',
    phoneCode: '+262',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/yt.svg',
    timeZones: [CountryTimezone.MAYOTTE],
    offset: ['UTC +03:00'],
  },
  {
    id: 140,
    code: CountryCode.MEXICO,
    name: 'Mexico',
    nameAr: 'المكسيك',
    phoneCode: '+52',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/mx.svg',
    timeZones: [
      CountryTimezone.MEXICO_BAJASUR,
      CountryTimezone.EASTERN_STANDARD_TIME,
      CountryTimezone.MEXICO_CHIHUAHUA,
      CountryTimezone.MEXICO_HERMOSILLO,
      CountryTimezone.MEXICO_MAZATLAN,
      CountryTimezone.MEXICO_MEXICO_CITY,
      CountryTimezone.MEXICO_MONTERREY,
      CountryTimezone.MEXICO_OJINAGA,
      CountryTimezone.MEXICO_TIJUANA,
    ],
    offset: ['UTC -06:00', 'UTC -05:00', 'UTC -07:00', 'UTC -07:00', 'UTC -07:00', 'UTC -06:00', 'UTC -06:00', 'UTC -07:00', 'UTC -08:00'],
  },
  {
    id: 141,
    code: CountryCode.MICRONESIA,
    name: 'Micronesia',
    nameAr: 'ميكرونيسيا',
    phoneCode: '+691',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/fm.svg',
    timeZones: [CountryTimezone.MICRONESIA_CHUUK_TIME, CountryTimezone.MICRONESIA_KOSRAE_TIME, CountryTimezone.MICRONESIA_POHNPEI_TIME],
    offset: ['UTC +10:00', 'UTC +11:00', 'UTC +11:00'],
  },
  {
    id: 142,
    code: CountryCode.MOLDOVA,
    name: 'Moldova',
    nameAr: 'مولدوفا',
    phoneCode: '+373',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/md.svg',
    timeZones: [CountryTimezone.MOLDOVA],
    offset: ['UTC +02:00'],
  },
  {
    id: 143,
    code: CountryCode.MONACO,
    name: 'Monaco',
    nameAr: 'موناكو',
    phoneCode: '+377',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mc.svg',
    timeZones: [CountryTimezone.MONACO],
    offset: ['UTC +01:00'],
  },
  {
    id: 144,
    code: CountryCode.MONGOLIA,
    name: 'Mongolia',
    nameAr: 'منغوليا',
    phoneCode: '+976',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/mn.svg',
    timeZones: [CountryTimezone.CHOIBALSAN, CountryTimezone.HOVD_TIME, CountryTimezone.MONGOLIA],
    offset: ['UTC +08:00', 'UTC +07:00', 'UTC +08:00'],
  },
  {
    id: 145,
    code: CountryCode.MONTENEGRO,
    name: 'Montenegro',
    nameAr: 'الجبل الأسود',
    phoneCode: '+382',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/me.svg',
    timeZones: [CountryTimezone.MONTENEGRO],
    offset: ['UTC +01:00'],
  },
  {
    id: 146,
    code: CountryCode.MONTSERRAT,
    name: 'Montserrat',
    nameAr: 'مونتسرات',
    phoneCode: '+1-664',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ms.svg',
    timeZones: [CountryTimezone.MONTSERRAT],
    offset: ['UTC -04:00'],
  },
  {
    id: 147,
    code: CountryCode.MOROCCO,
    name: 'Morocco',
    nameAr: 'المغرب',
    phoneCode: '+212',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ma.svg',
    timeZones: [CountryTimezone.MOROCCO],
    offset: ['UTC +01:00'],
  },
  {
    id: 148,
    code: CountryCode.MOZAMBIQUE,
    name: 'Mozambique',
    nameAr: 'موزمبيق',
    phoneCode: '+258',
    phoneMinLength: 12,
    phoneMaxLength: 12,
    flag: 'assets/countries-flag/svg/mz.svg',
    timeZones: [CountryTimezone.MOZAMBIQUE],
    offset: ['UTC +02:00'],
  },
  {
    id: 149,
    code: CountryCode.MYANMAR,
    name: 'Myanmar',
    nameAr: '(بورما) ميانمار',
    phoneCode: '+95',
    phoneMinLength: 8,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/mm.svg',
    timeZones: [CountryTimezone.MYANMAR],
    offset: ['UTC +06:30'],
  },
  {
    id: 150,
    code: CountryCode.NAMIBIA,
    name: 'Namibia',
    nameAr: 'ناميبيا',
    phoneCode: '+264',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/na.svg',
    timeZones: [CountryTimezone.NAMIBIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 151,
    code: CountryCode.NAURU,
    name: 'Nauru',
    nameAr: 'ناورو',
    phoneCode: '+674',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/nr.svg',
    timeZones: [CountryTimezone.NAURU],
    offset: ['UTC +12:00'],
  },
  {
    id: 152,
    code: CountryCode.NEPAL,
    name: 'Nepal',
    nameAr: 'نيبال',
    phoneCode: '+977',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/np.svg',
    timeZones: [CountryTimezone.NEPAL],
    offset: ['UTC +05:45'],
  },
  {
    id: 153,
    code: CountryCode.NETHERLANDS,
    name: 'Netherlands',
    nameAr: 'هولندا',
    phoneCode: '+31',
    phoneMinLength: 8,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/nl.svg',
    timeZones: [CountryTimezone.NETHERLANDS],
    offset: ['UTC +01:00'],
  },
  {
    id: 154,
    code: CountryCode.NEW_CALEDONIA,
    name: 'New Caledonia',
    nameAr: 'كاليدونيا الجديدة',
    phoneCode: '+687',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/nc.svg',
    timeZones: [CountryTimezone.NEW_CALEDONIA],
    offset: ['UTC +11:00'],
  },
  {
    id: 155,
    code: CountryCode.NEW_ZEALAND,
    name: 'New Zealand',
    nameAr: 'نيوزيلندا',
    phoneCode: '+64',
    phoneMinLength: 8,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/nz.svg',
    timeZones: [CountryTimezone.NEW_ZEALAND, CountryTimezone.CHATHAM_ISLAND_STANDARD_TIME],
    offset: ['UTC +13:00', 'UTC +13:45'],
  },
  {
    id: 156,
    code: CountryCode.NICARAGUA,
    name: 'Nicaragua',
    nameAr: 'نيكاراجوا',
    phoneCode: '+505',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ni.svg',
    timeZones: [CountryTimezone.NICARAGUA],
    offset: ['UTC -06:00'],
  },
  {
    id: 157,
    code: CountryCode.NIGER,
    name: 'Niger',
    nameAr: 'النيجر',
    phoneCode: '+227',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/ne.svg',
    timeZones: [CountryTimezone.NIGER],
    offset: ['UTC +01:00'],
  },
  {
    id: 158,
    code: CountryCode.NIGERIA,
    name: 'Nigeria',
    nameAr: 'نيجيريا',
    phoneCode: '+234',
    phoneMinLength: 8,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ng.svg',
    timeZones: [CountryTimezone.NIGERIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 159,
    code: CountryCode.NIUE,
    name: 'Niue',
    nameAr: 'نييوي',
    phoneCode: '+683',
    phoneMinLength: 4,
    phoneMaxLength: 4,
    flag: 'assets/countries-flag/svg/nu.svg',
    timeZones: [CountryTimezone.NIUE],
    offset: ['UTC -11:00'],
  },
  {
    id: 160,
    code: CountryCode.NORFOLK_ISLAND,
    name: 'Norfolk Island',
    nameAr: 'جزيرة نورفولك',
    phoneCode: '+672',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/nf.svg',
    timeZones: [CountryTimezone.NORFOLK_ISLAND],
    offset: ['UTC +11:00'],
  },
  {
    id: 161,
    code: CountryCode.NORTH_KOREA,
    name: 'North Korea',
    nameAr: 'كوريا الشمالية',
    phoneCode: '+850',
    phoneMinLength: 4,
    phoneMaxLength: 13,
    flag: 'assets/countries-flag/svg/kp.svg',
    timeZones: [CountryTimezone.NORTH_KOREA],
    offset: ['UTC +09:00'],
  },
  {
    id: 162,
    code: CountryCode.NORTHERN_MARIANA_ISLANDS,
    name: 'Northern Mariana Islands',
    nameAr: 'جزر ماريانا الشمالية',
    phoneCode: '+1-670',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/mp.svg',
    timeZones: [CountryTimezone.NORTHERN_MARIANA_ISLANDS],
    offset: ['UTC +10:00'],
  },
  {
    id: 163,
    code: CountryCode.NORWAY,
    name: 'Norway',
    nameAr: 'النرويج',
    phoneCode: '+47',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/no.svg',
    timeZones: [CountryTimezone.NORWAY],
    offset: ['UTC +01:00'],
  },
  {
    id: 164,
    code: CountryCode.OMAN,
    name: 'Oman',
    nameAr: 'عُمان',
    phoneCode: '+968',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/om.svg',
    timeZones: [CountryTimezone.OMAN],
    offset: ['UTC +04:00'],
  },
  {
    id: 165,
    code: CountryCode.PAKISTAN,
    name: 'Pakistan',
    nameAr: 'باكستان',
    phoneCode: '+92',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/pk.svg',
    timeZones: [CountryTimezone.PAKISTAN],
    offset: ['UTC +05:00'],
  },
  {
    id: 166,
    code: CountryCode.PALAU,
    name: 'Palau',
    nameAr: 'بالاو',
    phoneCode: '+680',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/pw.svg',
    timeZones: [CountryTimezone.PALAU],
    offset: ['UTC +09:00'],
  },
  {
    id: 167,
    code: CountryCode.PANAMA,
    name: 'Panama',
    nameAr: 'بنما',
    phoneCode: '+507',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/pa.svg',
    timeZones: [CountryTimezone.PANAMA],
    offset: ['UTC -05:00'],
  },
  {
    id: 168,
    code: CountryCode.PAPUA_NEW_GUINEA,
    name: 'Papua New Guinea',
    nameAr: 'بابوا غينيا الجديدة',
    phoneCode: '+675',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/pg.svg',
    timeZones: [CountryTimezone.BOUGAINVILLE_STANDARD_TIME, CountryTimezone.PAPUA_NEW_GUINEA],
    offset: ['UTC +11:00', 'UTC +10:00'],
  },
  {
    id: 169,
    code: CountryCode.PARAGUAY,
    name: 'Paraguay',
    nameAr: 'باراغواي',
    phoneCode: '+595',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/py.svg',
    timeZones: [CountryTimezone.PARAGUAY],
    offset: ['UTC -03:00'],
  },
  {
    id: 170,
    code: CountryCode.PERU,
    name: 'Peru',
    nameAr: 'بيرو',
    phoneCode: '+51',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/pe.svg',
    timeZones: [CountryTimezone.PERU],
    offset: ['UTC -05:00'],
  },
  {
    id: 171,
    code: CountryCode.PHILIPPINES,
    name: 'Philippines',
    nameAr: 'الفلبين',
    phoneCode: '+63',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ph.svg',
    timeZones: [CountryTimezone.PHILIPPINES],
    offset: ['UTC +08:00'],
  },
  {
    id: 172,
    code: CountryCode.PITCAIRN,
    name: 'Pitcairn',
    nameAr: 'جزر بيتكيرن',
    phoneCode: '+64',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/pn.svg',
    timeZones: [CountryTimezone.PITCAIRN_ISLANDS],
    offset: ['UTC -08:00'],
  },
  {
    id: 173,
    code: CountryCode.POLAND,
    name: 'Poland',
    nameAr: 'بولندا',
    phoneCode: '+49',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/pl.svg',
    timeZones: [CountryTimezone.POLAND],
    offset: ['UTC +01:00'],
  },
  {
    id: 174,
    code: CountryCode.PORTUGAL,
    name: 'Portugal',
    nameAr: 'البرتغال',
    phoneCode: '+351',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/pt.svg',
    timeZones: [CountryTimezone.AZORES_TIME, CountryTimezone.MADEIRA, CountryTimezone.PORTUGAL],
    offset: ['UTC -01:00', 'UTC', 'UTC'],
  },
  {
    id: 175,
    code: CountryCode.PUERTO_RICO,
    name: 'Puerto Rico',
    nameAr: 'بورتوريكو',
    phoneCode: '+1-787, +1-939',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/pr.svg',
    timeZones: [CountryTimezone.PUERTO_RICO],
    offset: ['UTC -04:00'],
  },
  {
    id: 176,
    code: CountryCode.QATAR,
    name: 'Qatar',
    nameAr: 'قطر',
    phoneCode: '+974',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/qa.svg',
    timeZones: [CountryTimezone.QATAR],
    offset: ['UTC +03:00'],
  },
  {
    id: 177,
    code: CountryCode.REPUBLIC_OF_THE_CONGO,
    name: 'Republic of the Congo',
    nameAr: 'جمهورية الكونغو',
    phoneCode: '+242',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/cg.svg',
    timeZones: [CountryTimezone.REPUBLIC_OF_THE_CONGO],
    offset: ['UTC +01:00'],
  },
  {
    id: 178,
    code: CountryCode.REUNION,
    name: 'Reunion',
    nameAr: 'ريونيون',
    phoneCode: '+262',
    phoneMinLength: 9,
    phoneMaxLength: 12,
    flag: 'assets/countries-flag/svg/re.svg',
    timeZones: [CountryTimezone.REUNION],
    offset: ['UTC +04:00'],
  },
  {
    id: 179,
    code: CountryCode.ROMANIA,
    name: 'Romania',
    nameAr: 'رومانيا',
    phoneCode: '+40',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ro.svg',
    timeZones: [CountryTimezone.ROMANIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 180,
    code: CountryCode.RUSSIA,
    name: 'Russia',
    nameAr: 'روسيا',
    phoneCode: '+7',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/ru.svg',
    timeZones: [
      CountryTimezone.ANADYR_TIME,
      CountryTimezone.IRKUTSK_TIME,
      CountryTimezone.KAMCHATKA_TIME,
      CountryTimezone.MAGADAN_TIME,
      CountryTimezone.NOVOSIBIRSK_TIME,
      CountryTimezone.OMSK_STANDARD_TIME,
      CountryTimezone.SAKHALIN_TIME,
      CountryTimezone.SREDNEKOLYMSK_TIME,
      CountryTimezone.VLADIVOSTOK_TIME,
      CountryTimezone.YAKUTSK_TIME,
      CountryTimezone.YEKATERINBURG_TIME,
      CountryTimezone.EASTERN_EUROPEAN_TIME,
      CountryTimezone.RUSSIA,
      CountryTimezone.SAMARA_TIME,
    ],
    offset: [
      'UTC +12:00',
      'UTC +08:00',
      'UTC +12:00',
      'UTC +11:00',
      'UTC +07:00',
      'UTC +06:00',
      'UTC +11:00',
      'UTC +11:00',
      'UTC +10:00',
      'UTC +09:00',
      'UTC +05:00',
      'UTC +02:00',
      'UTC +03:00',
      'UTC +04:00',
    ],
  },
  {
    id: 181,
    code: CountryCode.RWANDA,
    name: 'Rwanda',
    nameAr: 'رواندا',
    phoneCode: '+250',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/rw.svg',
    timeZones: [CountryTimezone.RWANDA],
    offset: ['UTC +02:00'],
  },
  {
    id: 182,
    code: CountryCode.SAINT_BARTHÉLEMY,
    name: 'Saint Barthélemy',
    nameAr: 'سان بارتيلمي',
    phoneCode: '+590',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/bl.svg',
    timeZones: [CountryTimezone.SAINT_BARTHELEMY],
    offset: ['UTC -04:00'],
  },
  {
    id: 183,
    code: CountryCode.SAINT_HELENA,
    name: 'Saint Helena',
    nameAr: 'سانت هيلينا',
    phoneCode: '+290',
    phoneMinLength: 4,
    phoneMaxLength: 4,
    flag: 'assets/countries-flag/svg/sh.svg',
    timeZones: [CountryTimezone.SAINT_HELENA],
    offset: ['UTC'],
  },
  {
    id: 184,
    code: CountryCode.SAINT_KITTS_AND_NEVIS,
    name: 'Saint Kitts and Nevis',
    nameAr: 'سانت كيتس ونيفيس',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/kn.svg',
    timeZones: [CountryTimezone.SAINT_KITTS_AND_NEVIS],
    offset: ['UTC -04:00'],
  },
  {
    id: 185,
    code: CountryCode.SAINT_LUCIA,
    name: 'Saint Lucia',
    nameAr: 'سانت لوسيا',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/lc.svg',
    timeZones: [CountryTimezone.SAINT_LUCIA],
    offset: ['UTC -04:00'],
  },
  {
    id: 186,
    code: CountryCode.SAINT_MARTIN,
    name: 'Saint Martin',
    nameAr: 'سانت مارتن',
    phoneCode: '+590',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/mf.svg',
    timeZones: [CountryTimezone.SAINT_MARTIN],
    offset: ['UTC -04:00'],
  },
  {
    id: 187,
    code: CountryCode.SAINT_PIERRE_AND_MIQUELON,
    name: 'Saint Pierre and Miquelon',
    nameAr: 'سان بيير وميكلون',
    phoneCode: '+508',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/pm.svg',
    timeZones: [CountryTimezone.SAINT_PIERRE_AND_MIQUELON],
    offset: ['UTC -03:00'],
  },
  {
    id: 188,
    code: CountryCode.SAINT_VINCENT_AND_THE_GRENADINES,
    name: 'Saint Vincent and the Grenadines',
    nameAr: 'سانت فينسنت والغرينادين',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/vc.svg',
    timeZones: [CountryTimezone.SAINT_VINCENT_AND_THE_GRENADINES],
    offset: ['UTC -04:00'],
  },
  {
    id: 189,
    code: CountryCode.SAMOA,
    name: 'Samoa',
    nameAr: 'ساموا',
    phoneCode: '+685',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/ws.svg',
    timeZones: [CountryTimezone.SAMOA],
    offset: ['UTC +14:00'],
  },
  {
    id: 190,
    code: CountryCode.SAN_MARINO,
    name: 'San Marino',
    nameAr: 'سان مارينو',
    phoneCode: '+378',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/sm.svg',
    timeZones: [CountryTimezone.SAN_MARINO],
    offset: ['UTC +01:00'],
  },
  {
    id: 191,
    code: CountryCode.SAO_TOME_AND_PRINCIPE,
    name: 'Sao Tome and Principe',
    nameAr: 'ساو تومي وبرينسيب',
    phoneCode: '+239',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/st.svg',
    timeZones: [CountryTimezone.SAO_TOME_AND_PRINCIPE],
    offset: ['UTC +01:00'],
  },
  {
    id: 192,
    code: CountryCode.SAUDI_ARABIA,
    name: 'Saudi Arabia',
    nameAr: 'السعودية',
    phoneCode: '+966',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/sa.svg',
    timeZones: [CountryTimezone.SAUDI_ARABIA],
    offset: ['UTC +03:00'],
  },
  {
    id: 193,
    code: CountryCode.SENEGAL,
    name: 'Senegal',
    nameAr: 'السنغال',
    phoneCode: '+221',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/sn.svg',
    timeZones: [CountryTimezone.SENEGAL],
    offset: ['UTC'],
  },
  {
    id: 194,
    code: CountryCode.SERBIA,
    name: 'Serbia',
    nameAr: 'صربيا',
    phoneCode: '+381',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/rs.svg',
    timeZones: [CountryTimezone.SERBIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 195,
    code: CountryCode.SEYCHELLES,
    name: 'Seychelles',
    nameAr: 'سيشل',
    phoneCode: '+248',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/sc.svg',
    timeZones: [CountryTimezone.SEYCHELLES],
    offset: ['UTC +04:00'],
  },
  {
    id: 196,
    code: CountryCode.SIERRA_LEONE,
    name: 'Sierra Leone',
    nameAr: 'سيراليون',
    phoneCode: '+232',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/sl.svg',
    timeZones: [CountryTimezone.SIERRA_LEONE],
    offset: ['UTC'],
  },
  {
    id: 197,
    code: CountryCode.SINGAPORE,
    name: 'Singapore',
    nameAr: 'سنغافورة',
    phoneCode: '+65',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/sg.svg',
    timeZones: [CountryTimezone.SINGAPORE],
    offset: ['UTC +08:00'],
  },
  {
    id: 198,
    code: CountryCode.SINT_MAARTEN,
    name: 'Sint Maarten',
    nameAr: 'سانت مارتن',
    phoneCode: '+1-721',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/sx.svg',
    timeZones: [CountryTimezone.SINT_MAARTEN],
    offset: ['UTC -04:00'],
  },
  {
    id: 199,
    code: CountryCode.SLOVAKIA,
    name: 'Slovakia',
    nameAr: 'سلوفاكيا',
    phoneCode: '+421',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/sk.svg',
    timeZones: [CountryTimezone.SLOVAKIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 200,
    code: CountryCode.SLOVENIA,
    name: 'Slovenia',
    nameAr: 'سلوفينيا',
    phoneCode: '+368',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/si.svg',
    timeZones: [CountryTimezone.SLOVENIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 201,
    code: CountryCode.SOLOMON_ISLANDS,
    name: 'Solomon Islands',
    nameAr: 'جزر سليمان',
    phoneCode: '+677',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/sb.svg',
    timeZones: [CountryTimezone.SOLOMON_ISLANDS],
    offset: ['UTC +11:00'],
  },
  {
    id: 202,
    code: CountryCode.SOMALIA,
    name: 'Somalia',
    nameAr: 'الصومال',
    phoneCode: '+252',
    phoneMinLength: 7,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/so.svg',
    timeZones: [CountryTimezone.SOMALIA],
    offset: ['UTC +03:00'],
  },
  {
    id: 203,
    code: CountryCode.SOUTH_AFRICA,
    name: 'South Africa',
    nameAr: 'جنوب أفريقيا',
    phoneCode: '+27',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/za.svg',
    timeZones: [CountryTimezone.SOUTH_AFRICA],
    offset: ['UTC +02:00'],
  },
  {
    id: 204,
    code: CountryCode.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
    name: 'South Georgia and the South Sandwich Islands',
    nameAr: 'جنوب جورجيا',
    phoneCode: '+500',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/gs.svg',
    timeZones: [CountryTimezone.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS],
    offset: ['UTC -02:00'],
  },
  {
    id: 205,
    code: CountryCode.SOUTH_KOREA,
    name: 'South Korea',
    nameAr: 'كوريا الجنوبية',
    phoneCode: '+82',
    phoneMinLength: 9,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/kr.svg',
    timeZones: [CountryTimezone.SOUTH_KOREA],
    offset: ['UTC +09:00'],
  },
  {
    id: 206,
    code: CountryCode.SOUTH_SUDAN,
    name: 'South Sudan',
    nameAr: 'جنوب السودان',
    phoneCode: '+211',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/ss.svg',
    timeZones: [CountryTimezone.SOUTH_SUDAN],
    offset: ['UTC +03:00'],
  },
  {
    id: 207,
    code: CountryCode.SPAIN,
    name: 'Spain',
    nameAr: 'إسبانيا',
    phoneCode: '+34',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/es.svg',
    timeZones: [CountryTimezone.CEUTA, CountryTimezone.WESTERN_EUROPEAN_TIME, CountryTimezone.SPAIN],
    offset: ['UTC +01:00', 'UTC', 'UTC +01:00'],
  },
  {
    id: 208,
    code: CountryCode.SRI_LANKA,
    name: 'Sri Lanka',
    nameAr: 'سريلانكا',
    phoneCode: '+94',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/lk.svg',
    timeZones: [CountryTimezone.SRI_LANKA],
    offset: ['UTC +05:30'],
  },
  {
    id: 209,
    code: CountryCode.SUDAN,
    name: 'Sudan',
    nameAr: 'السودان',
    phoneCode: '+249',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/sd.svg',
    timeZones: [CountryTimezone.SUDAN],
    offset: ['UTC +02:00'],
  },
  {
    id: 210,
    code: CountryCode.SURINAME,
    name: 'Suriname',
    nameAr: 'سورينام',
    phoneCode: '+597',
    phoneMinLength: 6,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/sr.svg',
    timeZones: [CountryTimezone.SURINAME],
    offset: ['UTC -03:00'],
  },
  {
    id: 211,
    code: CountryCode.SVALBARD_AND_JAN_MAYEN,
    name: 'Svalbard and Jan Mayen',
    nameAr: 'سفالبارد ويان ماين',
    phoneCode: '+47',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/sj.svg',
    timeZones: [CountryTimezone.SVALBARD_AND_JAN_MAYEN],
    offset: ['UTC +01:00'],
  },
  {
    id: 212,
    code: CountryCode.SWAZILAND,
    name: 'Swaziland',
    nameAr: 'سوازيلند',
    phoneCode: '+268',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/sz.svg',
    timeZones: [CountryTimezone.SWAZILAND],
    offset: ['UTC +02:00'],
  },
  {
    id: 213,
    code: CountryCode.SWEDEN,
    name: 'Sweden',
    nameAr: 'السويد',
    phoneCode: '+46',
    phoneMinLength: 7,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/se.svg',
    timeZones: [CountryTimezone.SWEDEN],
    offset: ['UTC +01:00'],
  },
  {
    id: 214,
    code: CountryCode.SWITZERLAND,
    name: 'Switzerland',
    nameAr: 'سويسرا',
    phoneCode: '+41',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ch.svg',
    timeZones: [CountryTimezone.SWITZERLAND],
    offset: ['UTC +01:00'],
  },
  {
    id: 215,
    code: CountryCode.SYRIA,
    name: 'Syria',
    nameAr: 'سوريا',
    phoneCode: '+963',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/sy.svg',
    timeZones: [CountryTimezone.SYRIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 216,
    code: CountryCode.TAIWAN,
    name: 'Taiwan',
    nameAr: 'تايوان',
    phoneCode: '+886',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/tw.svg',
    timeZones: [CountryTimezone.TAIWAN],
    offset: ['UTC +08:00'],
  },
  {
    id: 217,
    code: CountryCode.TAJIKISTAN,
    name: 'Tajikistan',
    nameAr: 'طاجيكستان',
    phoneCode: '+992',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/tj.svg',
    timeZones: [CountryTimezone.TAJIKISTAN],
    offset: ['UTC +05:00'],
  },
  {
    id: 218,
    code: CountryCode.TANZANIA,
    name: 'Tanzania',
    nameAr: 'تنزانيا',
    phoneCode: '+255',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/tz.svg',
    timeZones: [CountryTimezone.TANZANIA],
    offset: ['UTC +03:00'],
  },
  {
    id: 219,
    code: CountryCode.THAILAND,
    name: 'Thailand',
    nameAr: 'تايلاند',
    phoneCode: '+66',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/th.svg',
    timeZones: [CountryTimezone.THAILAND],
    offset: ['UTC +07:00'],
  },
  {
    id: 220,
    code: CountryCode.TOGO,
    name: 'Togo',
    nameAr: 'توغو',
    phoneCode: '+228',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/tg.svg',
    timeZones: [CountryTimezone.TOGO],
    offset: ['UTC'],
  },
  {
    id: 221,
    code: CountryCode.TOKELAU,
    name: 'Tokelau',
    nameAr: 'توكيلاو',
    phoneCode: '+690',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/tk.svg',
    timeZones: [CountryTimezone.TOKELAU],
    offset: ['UTC +13:00'],
  },
  {
    id: 222,
    code: CountryCode.TONGA,
    name: 'Tonga',
    nameAr: 'تونغا',
    phoneCode: '+676',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/to.svg',
    timeZones: [CountryTimezone.TONGA],
    offset: ['UTC +13:00'],
  },
  {
    id: 223,
    code: CountryCode.TRINIDAD_AND_TOBAGO,
    name: 'Trinidad and Tobago',
    nameAr: 'ترينيداد وتوباغو',
    phoneCode: '+1-868',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/tt.svg',
    timeZones: [CountryTimezone.TRINIDAD_AND_TOBAGO],
    offset: ['UTC -04:00'],
  },
  {
    id: 224,
    code: CountryCode.TUNISIA,
    name: 'Tunisia',
    nameAr: 'تونس',
    phoneCode: '+216',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/tn.svg',
    timeZones: [CountryTimezone.TUNISIA],
    offset: ['UTC +01:00'],
  },
  {
    id: 225,
    code: CountryCode.TURKEY,
    name: 'Turkey',
    nameAr: 'تركيا',
    phoneCode: '+90',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/tr.svg',
    timeZones: [CountryTimezone.TURKEY],
    offset: ['UTC +03:00'],
  },
  {
    id: 226,
    code: CountryCode.TURKMENISTAN,
    name: 'Turkmenistan',
    nameAr: 'تركمانستان',
    phoneCode: '+993',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/tm.svg',
    timeZones: [CountryTimezone.TURKMENISTAN],
    offset: ['UTC +05:00'],
  },
  {
    id: 227,
    code: CountryCode.TURKS_AND_CAICOS_ISLANDS,
    name: 'Turks and Caicos Islands',
    nameAr: 'جزر توركس وكايكوس',
    phoneCode: '+1-649',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/tc.svg',
    timeZones: [CountryTimezone.TURKS_AND_CAICOS_ISLANDS],
    offset: ['UTC -05:00'],
  },
  {
    id: 228,
    code: CountryCode.TUVALU,
    name: 'Tuvalu',
    nameAr: 'توفالو',
    phoneCode: '+688',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/tv.svg',
    timeZones: [CountryTimezone.TUVALU],
    offset: ['UTC +12:00'],
  },
  {
    id: 229,
    code: CountryCode.UNITED_STATES_VIRGIN_ISLANDS,
    name: 'U.S. Virgin Islands',
    nameAr: 'جزر العذراء الأمريكية',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/vi.svg',
    timeZones: [CountryTimezone.US_VIRGIN_ISLANDS],
    offset: ['UTC -04:00'],
  },
  {
    id: 230,
    code: CountryCode.UGANDA,
    name: 'Uganda',
    nameAr: 'أوغندا',
    phoneCode: '+256',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/ug.svg',
    timeZones: [CountryTimezone.UGANDA],
    offset: ['UTC +03:00'],
  },
  {
    id: 231,
    code: CountryCode.UKRAINE,
    name: 'Ukraine',
    nameAr: 'أوكرانيا',
    phoneCode: '+380',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ua.svg',
    timeZones: [CountryTimezone.UKRAINE, CountryTimezone.UZHGOROD, CountryTimezone.ZAPOROZHYE],
    offset: ['UTC +02:00', 'UTC +02:00', 'UTC +02:00'],
  },
  {
    id: 232,
    code: CountryCode.UNITED_ARAB_EMIRATES,
    name: 'United Arab Emirates',
    nameAr: 'الإمارات العربية المتحدة',
    phoneCode: '+971',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ae.svg',
    timeZones: [CountryTimezone.UNITED_ARAB_EMIRATES],
    offset: ['UTC +04:00'],
  },
  {
    id: 233,
    code: CountryCode.UNITED_KINGDOM,
    name: 'United Kingdom',
    nameAr: 'المملكة المتحدة',
    phoneCode: '+44',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/gb.svg',
    timeZones: [CountryTimezone.UNITED_KINGDOM],
    offset: ['UTC'],
  },
  {
    id: 234,
    code: CountryCode.UNITED_STATES,
    name: 'United States',
    nameAr: 'الولايات المتحدة',
    phoneCode: '+1',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/us.svg',
    timeZones: [
      // CountryTimezone.undefined,'America/Adak',
      // CountryTimezone.ALASKA_STANDARD_TIME,'America/Anchorage',
      // CountryTimezone.undefined,'America/Boise',
      // CountryTimezone.CHICAGO_CENTRAL_STANDARD_TIME,'America/Chicago',
      // CountryTimezone.DENVER_MOUNTAIN_STANDARD_TIME,'America/Denver',
      // CountryTimezone.undefined,'America/Detroit',
      // CountryTimezone.undefined,'America/Indiana/Indianapolis',
      // CountryTimezone.undefined,'America/Indiana/Knox',
      // CountryTimezone.undefined,'America/Indiana/Marengo',
      // CountryTimezone.undefined,'America/Indiana/Petersburg',
      // CountryTimezone.undefined,'America/Indiana/Tell_City',
      // CountryTimezone.undefined,'America/Indiana/Vevay',
      // CountryTimezone.undefined,'America/Indiana/Vincennes',
      // CountryTimezone.undefined,'America/Indiana/Winamac',
      // CountryTimezone.undefined,'America/Juneau',
      // CountryTimezone.undefined,'America/Kentucky/Louisville',
      // CountryTimezone.undefined,'America/Kentucky/Monticello',
      // CountryTimezone.LOS_ANGELES_PACIFIC_STANDARD_TIME,'America/Los_Angeles',
      // CountryTimezone.undefined,'America/Menominee',
      // CountryTimezone.undefined,'America/Metlakatla',
      // CountryTimezone.UNITED_STATES,'America/New_York',
      // CountryTimezone.undefined,'America/Nome',
      // CountryTimezone.undefined,'America/North_Dakota/Beulah',
      // CountryTimezone.undefined,'America/North_Dakota/Center',
      // CountryTimezone.undefined,'America/North_Dakota/New_Salem',
      // CountryTimezone.undefined,'America/Phoenix',
      // CountryTimezone.undefined,'America/Sitka',
      // CountryTimezone.undefined,'America/Yakutat',
      // CountryTimezone.HAWAII_STANDARD_TIME,'Pacific/Honolulu',
    ],
    offset: [
      'UTC -10:00',
      'UTC -09:00',
      'UTC -07:00',
      'UTC -06:00',
      'UTC -07:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -06:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -06:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -09:00',
      'UTC -05:00',
      'UTC -05:00',
      'UTC -08:00',
      'UTC -06:00',
      'UTC -09:00',
      'UTC -05:00',
      'UTC -09:00',
      'UTC -06:00',
      'UTC -06:00',
      'UTC -06:00',
      'UTC -07:00',
      'UTC -09:00',
      'UTC -09:00',
      'UTC -10:00',
    ],
  },
  {
    id: 235,
    code: CountryCode.UNITED_STATES_MINOR_OUTLYING_ISLANDS,
    name: 'United States Minor Outlying Islands',
    nameAr: 'جزر الولايات المتحدة البعيدة الصغرى',
    phoneCode: '+849',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: '',
    timeZones: [CountryTimezone.SAMOA_STANDARD_TIME, CountryTimezone.ANYWHERE_ON_EARTH],
    offset: ['UTC -11:00', 'UTC +12:00'],
  },
  {
    id: 236,
    code: CountryCode.URUGUAY,
    name: 'Uruguay',
    nameAr: 'أوروغواي',
    phoneCode: '+598',
    phoneMinLength: 8,
    phoneMaxLength: 8,
    flag: 'assets/countries-flag/svg/uy.svg',
    timeZones: [CountryTimezone.URUGUAY],
    offset: ['UTC -03:00'],
  },
  {
    id: 237,
    code: CountryCode.UZBEKISTAN,
    name: 'Uzbekistan',
    nameAr: 'أوزبكستان',
    phoneCode: '+998',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/uz.svg',
    timeZones: [CountryTimezone.SAMARKAND, CountryTimezone.UZBEKISTAN],
    offset: ['UTC +05:00', 'UTC +05:00'],
  },
  {
    id: 238,
    code: CountryCode.VANUATU,
    name: 'Vanuatu',
    nameAr: 'فانواتو',
    phoneCode: '+678',
    phoneMinLength: 5,
    phoneMaxLength: 5,
    flag: 'assets/countries-flag/svg/vu.svg',
    timeZones: [CountryTimezone.VANUATU],
    offset: ['UTC +11:00'],
  },
  {
    id: 239,
    code: CountryCode.VATICAN,
    name: 'Vatican',
    nameAr: 'الفاتيكان',
    phoneCode: '+379',
    phoneMinLength: 10,
    phoneMaxLength: 10,
    flag: 'assets/countries-flag/svg/va.svg',
    timeZones: [CountryTimezone.VATICAN],
    offset: ['UTC +01:00'],
  },
  {
    id: 240,
    code: CountryCode.VENEZUELA,
    name: 'Venezuela',
    nameAr: 'فنزويلا',
    phoneCode: '+58',
    phoneMinLength: 7,
    phoneMaxLength: 7,
    flag: 'assets/countries-flag/svg/ve.svg',
    timeZones: [CountryTimezone.VENEZUELA],
    offset: ['UTC -04:00'],
  },
  {
    id: 241,
    code: CountryCode.VIETNAM,
    name: 'Vietnam',
    nameAr: 'فيتنام',
    phoneCode: '+84',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/vn.svg',
    timeZones: [CountryTimezone.VIETNAM],
    offset: ['UTC +07:00'],
  },
  {
    id: 242,
    code: CountryCode.WALLIS_AND_FUTUNA,
    name: 'Wallis and Futuna',
    nameAr: 'واليس وفوتونا',
    phoneCode: '+681',
    phoneMinLength: 6,
    phoneMaxLength: 6,
    flag: 'assets/countries-flag/svg/wf.svg',
    timeZones: [CountryTimezone.WALLIS_AND_FUTUNA],
    offset: ['UTC +12:00'],
  },
  {
    id: 243,
    code: CountryCode.WESTERN_SAHARA,
    name: 'Western Sahara',
    nameAr: 'الصحراء الغربية',
    phoneCode: '+212',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/eh.svg',
    timeZones: [CountryTimezone.WESTERN_SAHARA],
    offset: ['UTC +01:00'],
  },
  {
    id: 244,
    code: CountryCode.YEMEN,
    name: 'Yemen',
    nameAr: 'اليمن',
    phoneCode: '+967',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/ye.svg',
    timeZones: [CountryTimezone.YEMEN],
    offset: ['UTC +03:00'],
  },
  {
    id: 245,
    code: CountryCode.ZAMBIA,
    name: 'Zambia',
    nameAr: 'زامبيا',
    phoneCode: '+260',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/zm.svg',
    timeZones: [CountryTimezone.ZAMBIA],
    offset: ['UTC +02:00'],
  },
  {
    id: 246,
    code: CountryCode.ZIMBABWE,
    name: 'Zimbabwe',
    nameAr: 'زيمبابوى',
    phoneCode: '+263',
    phoneMinLength: 9,
    phoneMaxLength: 9,
    flag: 'assets/countries-flag/svg/zw.svg',
    timeZones: [CountryTimezone.ZIMBABWE],
    offset: ['UTC +02:00'],
  },
];
