export const FIRESTORE_PROVIDER = 'FIRESTORE_PROVIDER';
export const FIRESTORE_OPTIONS_PROVIDER = 'FIRESTORE_OPTIONS_PROVIDER';
export enum FIRESTORE_COLLECTION_PROVIDERS {}

export const FIRESTORE_QUERY_MAX_LIMIT = 1e2;
