export enum JWT_SERVICE_PROVIDERS {
  INVOICES = 'JWT_INVOICES',
  CLIENTS = 'JWT_CLIENTS',
  ORGANIZATIONS = 'JWT_ORGANIZATIONS',
}

export const JWT_SECRETS = [process.env.INVOICES_JWT_SECRET, process.env.CLIENTS_JWT_SECRET, process.env.ORGANIZATIONS_JWT_SECRET];
export const JWT_PROVIDERS = [JWT_SERVICE_PROVIDERS.INVOICES, JWT_SERVICE_PROVIDERS.CLIENTS, JWT_SERVICE_PROVIDERS.ORGANIZATIONS];
