export const HTTP_PROVIDER = 'HTTP_PROVIDER';
export const REDIS_PROVIDER = 'REDIS';
export const EVENT_EMITTER_PROVIDER = 'EVENT_EMITTER';
export const LOCKER_PROVIDER = 'LOCKER';

export const AUTH_CONFIGS_PROVIDER = 'AUTH_CONFIGS';
export const AUTH_APP_PROVIDER = 'AUTH_APP';
export const AUTH_STRATEGY = 'AUTH_STRATEGY';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';

export const CLOUD_TASKS_PROVIDER = 'CLOUD_TASKS';

export const ETA_CONFIGS_PROVIDER = 'ETA_CONFIGS_PROVIDER';
export const ETA_PROVIDER = 'ETA_PROVIDER';
export const ETA_COMMON_PROVIDER = 'ETA_COMMON_PROVIDER';
export const ETA_E_INVOICING_PROVIDER = 'ETA_E_INVOICING_PROVIDER';
