export const HTTP_PROVIDER = 'HTTP_PROVIDER';
export const REDIS_PROVIDER = 'REDIS';
export const EVENT_EMITTER_PROVIDER = 'EVENT_EMITTER';

export const AUTH_CONFIGS_PROVIDER = 'AUTH_CONFIGS';
export const AUTH_APP_PROVIDER = 'AUTH_APP';
export const AUTH_STRATEGY = 'AUTH_STRATEGY';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';
