export const HTTP_PROVIDER = 'HTTP_PROVIDER';
export const REDIS_PROVIDER = 'REDIS';
export const EVENT_EMITTER_PROVIDER = 'EVENT_EMITTER';

// ** Passport Auth **
export const AUTH_STRATEGY = 'AUTH_STRATEGY';
export const AUTH_PROVIDER = 'AUTH_PROVIDER';

// ** Google **

export const FIRE_AUTH_CONFIGS_PROVIDER = 'FIRE_AUTH_CONFIGS_PROVIDER';
export const FIRE_AUTH_PROVIDER = 'FIRE_AUTH_PROVIDER';

export const CLOUD_TASKS_PROVIDER = 'CLOUD_TASKS';

export const GMAIL_CONFIGS_PROVIDER = 'GMAIL_CONFIGS_PROVIDER';
export const GMAIL_TRANSPORTER_PROVIDER = 'GMAIL_TRANSPORTER_PROVIDER';
export const GMAIL_PROVIDER = 'GMAIL_PROVIDER';
export const GMAIL_QUEUE_PROVIDER = 'GMAIL_QUEUE_PROVIDER';

// ** ETA **
export const ETA_CONFIGS_PROVIDER = 'ETA_CONFIGS_PROVIDER';
export const ETA_PROVIDER = 'ETA_PROVIDER';
export const ETA_COMMON_PROVIDER = 'ETA_COMMON_PROVIDER';
export const ETA_E_INVOICING_PROVIDER = 'ETA_E_INVOICING_PROVIDER';
export const ETA_E_RECEIPT_PROVIDER = 'ETA_E_RECEIPT_PROVIDER';

// ** Stripe **
export const STRIPE_PROVIDER = Symbol('STRIPE_PROVIDER');

// ** PayTabs **
export const PAY_TABS_PROVIDER = 'PAY_TABS_PROVIDER';

// ** Paypal **
export const PAYPAL_CONFIGS_PROVIDER = 'PAYPAL_CONFIGS_PROVIDER';
export const PAYPAL_PROVIDER = 'PAYPAL_PROVIDER';

// ** EasyKash **
export const EASY_KASH_CONFIGS_PROVIDER = 'EASY_KASH_CONFIGS_PROVIDER';
export const EASY_KASH_PROVIDER = 'EASY_KASH_PROVIDER';
