export const SUBSCRIPTION_PLAN_REPOSITORY_PROVIDER = 'SUBSCRIPTION_PLAN_REPOSITORY';
export const SUBSCRIPTION_PLAN_SERVICE_PROVIDER = 'SUBSCRIPTION_PLAN_SERVICE';
export const SUBSCRIPTION_PLAN_USECASE_PROVIDERS = {
  ADD_SUBSCRIPTION_PLAN: 'ADD_SUBSCRIPTION_PLAN',
  GET_SUBSCRIPTION_PLAN: 'GET_SUBSCRIPTION_PLAN',
  GET_SUBSCRIPTION_PLANS: 'GET_SUBSCRIPTION_PLANS',
  UPDATE_SUBSCRIPTION_PLAN: 'UPDATE_SUBSCRIPTION_PLAN',
};
