export const SUBSCRIPTION_REPOSITORY_PROVIDER = 'SUBSCRIPTION_REPOSITORY';
export const SUBSCRIPTION_SERVICE_PROVIDER = 'SUBSCRIPTION_SERVICE';
export const SUBSCRIPTION_USECASE_PROVIDERS = {
  ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
  GET_SUBSCRIPTION: 'GET_SUBSCRIPTION',
  GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
  UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION',
  CANCELED_SUBSCRIPTION: 'CANCELED_SUBSCRIPTION',
};
