export const SUBSCRIPTION_REPOSITORY_PROVIDER = 'SUBSCRIPTION_REPOSITORY';
export const SUBSCRIPTION_SERVICE_PROVIDER = 'SUBSCRIPTION_SERVICE';
export const SUBSCRIPTION_USECASE_PROVIDERS = {
  ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
  GET_SUBSCRIPTION: 'GET_SUBSCRIPTION',
  CANCELED_SUBSCRIPTION: 'CANCELED_SUBSCRIPTION',
};

export const SUBSCRIPTION_USAGE_REPOSITORY_PROVIDER = 'SUBSCRIPTION_USAGE_REPOSITORY';
export const SUBSCRIPTION_USAGE_SERVICE_PROVIDER = 'SUBSCRIPTION_USAGE_SERVICE';
