export const ACCOUNT_PREFERENCES_REPOSITORY_PROVIDER = 'ACCOUNT_PREFERENCES_REPOSITORY';
export const ACCOUNT_PREFERENCES_SERVICE_PROVIDER = 'ACCOUNT_PREFERENCES_SERVICE';
export const ACCOUNT_PREFERENCES_USECASE_PROVIDERS = {
  GET_ACCOUNT_PREFERENCES: 'GET_ACCOUNT_PREFERENCES',
  UPDATE_ACCOUNT_PREFERENCES: 'UPDATE_ACCOUNT_PREFERENCES',
};
