export const ACCOUNT_REPOSITORY_PROVIDER = 'ACCOUNT_REPOSITORY';
export const ACCOUNT_SERVICE_PROVIDER = 'ACCOUNT_SERVICE';
export const ACCOUNT_USECASE_PROVIDERS = {
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  GET_ACCOUNT: 'GET_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
};
