export const CLIENT_PREFERENCES_REPOSITORY_PROVIDER = 'CLIENT_PREFERENCES_REPOSITORY';
export const CLIENT_PREFERENCES_SERVICE_PROVIDER = 'CLIENT_PREFERENCES_SERVICE';
export const CLIENT_PREFERENCES_USECASE_PROVIDERS = {
  GET_CLIENT_PREFERENCES: 'GET_CLIENT_PREFERENCES',
  UPDATE_CLIENT_PREFERENCES: 'UPDATE_CLIENT_PREFERENCES',
};
