export const CLIENT_REPOSITORY_PROVIDER = 'CLIENT_REPOSITORY';
export const CLIENT_SERVICE_PROVIDER = 'CLIENT_SERVICE';
export const CLIENT_USECASE_PROVIDERS = {
  ADD_CLIENT: 'ADD_CLIENT',
  ADD_CLIENTS: 'ADD_CLIENTS',
  GET_CLIENT: 'GET_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  GET_CLIENTS: 'GET_CLIENTS',
  GET_ORGANIZATION_CLIENTS: 'GET_ORGANIZATION_CLIENTS',
  VALIDATE_CLIENT_TAX_NUMBER: 'VALIDATE_CLIENT_TAX_NUMBER',
};
