export const CLIENT_REPOSITORY_PROVIDER = 'CLIENT_REPOSITORY';
export const CLIENT_SERVICE_PROVIDER = 'CLIENT_SERVICE';
export const CLIENT_USECASE_PROVIDERS = {
  ADD_CLIENT: 'ADD_CLIENT',
  ADD_CLIENTS: 'ADD_CLIENTS',
  GET_CLIENT: 'GET_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  QUERY_CLIENTS: 'QUERY_CLIENTS',
};
