export const USER_REPOSITORY_PROVIDER = 'USER_REPOSITORY';
export const USER_SERVICE_PROVIDER = 'USER_SERVICE';
export const USER_USECASE_PROVIDERS = {
  REGISTER_USER: 'REGISTER_USER',
  ADD_USER: 'ADD_USER',
  GET_USER: 'GET_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
  QUERY_USERS: 'QUERY_USERS',
  GET_USER_ACCOUNTS: 'GET_USER_ACCOUNTS',
};
