export const USER_PREFERENCES_REPOSITORY_PROVIDER = 'USER_PREFERENCES_REPOSITORY';
export const USER_PREFERENCES_SERVICE_PROVIDER = 'USER_PREFERENCES_SERVICE';
export const USER_PREFERENCES_USECASE_PROVIDERS = {
  GET_USER_PREFERENCES: 'GET_USER_PREFERENCES',
  UPDATE_USER_PREFERENCES: 'UPDATE_USER_PREFERENCES',
};
