export const USER_NOTIFICATION_REPOSITORY_PROVIDER = 'USER_NOTIFICATION_REPOSITORY';
export const USER_NOTIFICATION_SERVICE_PROVIDER = 'USER_NOTIFICATION_SERVICE';
export const USER_NOTIFICATION_USECASE_PROVIDERS = {
  GET_USER_NOTIFICATIONS: 'GET_USER_NOTIFICATIONS',
  MARK_ALL_AS_READ: 'MARK_ALL_AS_READ',
  MARK_AS_READ: 'MARK_AS_READ',
  MARK_AS_UNREAD: 'MARK_AS_UNREAD',
};
