export const BILLING_ACCOUNT_REPOSITORY_PROVIDER = 'BILLING_ACCOUNT_REPOSITORY';
export const BILLING_ACCOUNT_SERVICE_PROVIDER = 'BILLING_ACCOUNT_SERVICE';
export const BILLING_ACCOUNT_USECASE_PROVIDERS = {
  ADD_BILLING_ACCOUNT: 'ADD_BILLING_ACCOUNT',
  GET_BILLING_ACCOUNT: 'GET_BILLING_ACCOUNT',
  DELETE_BILLING_ACCOUNT: 'DELETE_BILLING_ACCOUNT',
  UPDATE_BILLING_ACCOUNT: 'UPDATE_BILLING_ACCOUNT',
  GET_BILLING_ACCOUNTS: 'GET_BILLING_ACCOUNTS',
};
