export const BRANCH_REPOSITORY_PROVIDER = 'BRANCH_REPOSITORY';
export const BRANCH_SERVICE_PROVIDER = 'BRANCH_SERVICE';
export const BRANCH_USECASE_PROVIDERS = {
  ADD_BRANCH: 'ADD_BRANCH',
  GET_BRANCH: 'GET_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  GET_BRANCHES: 'GET_BRANCHES',
};
