export const ORGANIZATION_REPOSITORY_PROVIDER = 'ORGANIZATION_REPOSITORY';
export const ORGANIZATION_SERVICE_PROVIDER = 'ORGANIZATION_SERVICE';
export const ORGANIZATION_USECASE_PROVIDERS = {
  ADD_ORGANIZATION: 'ADD_ORGANIZATION',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  GET_ORGANIZATIONS: 'GET_ORGANIZATIONS',
};

export const ORGANIZATION_TAX_REPOSITORY_PROVIDER = 'ORGANIZATION_TAX_REPOSITORY';
export const ORGANIZATION_TAX_SERVICE_PROVIDER = 'ORGANIZATION_TAX_SERVICE';
export const ORGANIZATION_TAX_USECASE_PROVIDERS = {
  GET_ORGANIZATION_TAX: 'GET_ORGANIZATION_TAX',
  VALIDATE_AUTHORITY_TAX_NUMBER: 'VALIDATE_AUTHORITY_TAX_NUMBER',
  UPDATE_ORGANIZATION_TAX: 'UPDATE_ORGANIZATION_TAX',
  ASSIGN_ORGANIZATION_TAX: 'ASSIGN_ORGANIZATION_TAX',
};
