export const ORGANIZATION_REPOSITORY_PROVIDER = 'ORGANIZATION_REPOSITORY';
export const ORGANIZATION_SERVICE_PROVIDER = 'ORGANIZATION_SERVICE';
export const ORGANIZATION_USECASE_PROVIDERS = {
  ADD_ORGANIZATION: 'ADD_ORGANIZATION',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  QUERY_ORGANIZATIONS: 'QUERY_ORGANIZATIONS',
  GET_ORGANIZATION_ACCOUNTS: 'GET_ORGANIZATION_ACCOUNTS',
};
