export const ORGANIZATION_PREFERENCES_REPOSITORY_PROVIDER = 'ORGANIZATION_PREFERENCES_REPOSITORY';
export const ORGANIZATION_PREFERENCES_SERVICE_PROVIDER = 'ORGANIZATION_PREFERENCES_SERVICE';
export const ORGANIZATION_PREFERENCES_USECASE_PROVIDERS = {
  GET_ORGANIZATION_PREFERENCES: 'GET_ORGANIZATION_PREFERENCES',
  UPDATE_ORGANIZATION_PREFERENCES: 'UPDATE_ORGANIZATION_PREFERENCES',
};
