export const PRODUCT_REPOSITORY_PROVIDER = 'PRODUCT_REPOSITORY';
export const PRODUCT_SERVICE_PROVIDER = 'PRODUCT_SERVICE';
export const PRODUCT_USECASE_PROVIDERS = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  GET_PRODUCT: 'GET_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  DRAFT_PRODUCT: 'DRAFT_PRODUCT',
};
