export const ETA_EINVOICING_QUEUE_PROVIDER = 'ETA_EINVOICING_QUEUE';
export const ETA_INVOICE_SERVICE_PROVIDER = 'ETA_INVOICE_SERVICE';
export const ETA_INVOICE_PROCESSOR_PROVIDER = 'ETA_INVOICE_PROCESSOR';

export const ETA_INVOICE_USECASE_PROVIDERS = {
  SUBMIT_INVOICES: 'SUBMIT_INVOICES',
  CANCEL_INVOICE: 'CANCEL_INVOICE',
  PROCESS_INVOICE: 'PROCESS_INVOICE',
  ACCEPT_INVOICE: 'ACCEPT_INVOICE',
};
