export const INVOICE_REPOSITORY_PROVIDER = 'INVOICE_REPOSITORY';
export const INVOICE_SERVICE_PROVIDER = 'INVOICE_SERVICE';
export const INVOICE_ITEM_REPOSITORY_PROVIDER = 'INVOICE_ITEM_REPOSITORY';
export const INVOICE_SUBMISSION_REPOSITORY_PROVIDER = 'INVOICE_SUBMISSION_REPOSITORY';
export const INVOICE_USECASE_PROVIDERS = {
  ADD_INVOICE: 'ADD_INVOICE',
  GET_INVOICE: 'GET_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  GET_INVOICE_ITEMS: 'GET_INVOICE_ITEMS',
  QUERY_INVOICES: 'QUERY_INVOICES',

  GET_ORGANIZATION_INVOICES: 'GET_ORGANIZATION_INVOICES',
  GET_CLIENT_INVOICES: 'GET_CLIENT_INVOICES',
  // SHARE_INVOICE: 'SHARE_INVOICE',
};
